// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.3
// source: pkg/proto/telemetry/v1/telemetry_analytics.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggregationType int32

const (
	AggregationType_AGGREGATION_TYPE_UNSPECIFIED AggregationType = 0
	AggregationType_AGGREGATION_TYPE_COUNT       AggregationType = 1
	AggregationType_AGGREGATION_TYPE_AVG         AggregationType = 2
	AggregationType_AGGREGATION_TYPE_MIN         AggregationType = 3
	AggregationType_AGGREGATION_TYPE_MAX         AggregationType = 4
	AggregationType_AGGREGATION_TYPE_SUM         AggregationType = 5
	AggregationType_AGGREGATION_TYPE_CARDINALITY AggregationType = 6
)

// Enum value maps for AggregationType.
var (
	AggregationType_name = map[int32]string{
		0: "AGGREGATION_TYPE_UNSPECIFIED",
		1: "AGGREGATION_TYPE_COUNT",
		2: "AGGREGATION_TYPE_AVG",
		3: "AGGREGATION_TYPE_MIN",
		4: "AGGREGATION_TYPE_MAX",
		5: "AGGREGATION_TYPE_SUM",
		6: "AGGREGATION_TYPE_CARDINALITY",
	}
	AggregationType_value = map[string]int32{
		"AGGREGATION_TYPE_UNSPECIFIED": 0,
		"AGGREGATION_TYPE_COUNT":       1,
		"AGGREGATION_TYPE_AVG":         2,
		"AGGREGATION_TYPE_MIN":         3,
		"AGGREGATION_TYPE_MAX":         4,
		"AGGREGATION_TYPE_SUM":         5,
		"AGGREGATION_TYPE_CARDINALITY": 6,
	}
)

func (x AggregationType) Enum() *AggregationType {
	p := new(AggregationType)
	*p = x
	return p
}

func (x AggregationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_enumTypes[0].Descriptor()
}

func (AggregationType) Type() protoreflect.EnumType {
	return &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_enumTypes[0]
}

func (x AggregationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregationType.Descriptor instead.
func (AggregationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{0}
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // RFC3339 or relative like "now-6h"
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // RFC3339 or "now"
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`                    // e.g. "UTC", "America/Los_Angeles"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TimeRange) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TimeRange) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type TelemetryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceTypeId  string                 `protobuf:"bytes,4,opt,name=device_type_id,json=deviceTypeId,proto3" json:"device_type_id,omitempty"`
	SensorIds     []string               `protobuf:"bytes,5,rep,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	Channels      []string               `protobuf:"bytes,6,rep,name=channels,proto3" json:"channels,omitempty"`
	EventTypes    []string               `protobuf:"bytes,7,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	DataTypes     []string               `protobuf:"bytes,8,rep,name=data_types,json=dataTypes,proto3" json:"data_types,omitempty"`
	CorrelationId string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ValueFilter   *ValueFilter           `protobuf:"bytes,10,opt,name=value_filter,json=valueFilter,proto3" json:"value_filter,omitempty"`
	GeoFilter     *GeoFilter             `protobuf:"bytes,11,opt,name=geo_filter,json=geoFilter,proto3" json:"geo_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryFilter) Reset() {
	*x = TelemetryFilter{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryFilter) ProtoMessage() {}

func (x *TelemetryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryFilter.ProtoReflect.Descriptor instead.
func (*TelemetryFilter) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryFilter) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TelemetryFilter) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *TelemetryFilter) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryFilter) GetDeviceTypeId() string {
	if x != nil {
		return x.DeviceTypeId
	}
	return ""
}

func (x *TelemetryFilter) GetSensorIds() []string {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

func (x *TelemetryFilter) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *TelemetryFilter) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *TelemetryFilter) GetDataTypes() []string {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *TelemetryFilter) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TelemetryFilter) GetValueFilter() *ValueFilter {
	if x != nil {
		return x.ValueFilter
	}
	return nil
}

func (x *TelemetryFilter) GetGeoFilter() *GeoFilter {
	if x != nil {
		return x.GeoFilter
	}
	return nil
}

type ValueFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *float64               `protobuf:"fixed64,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *float64               `protobuf:"fixed64,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueFilter) Reset() {
	*x = ValueFilter{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueFilter) ProtoMessage() {}

func (x *ValueFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueFilter.ProtoReflect.Descriptor instead.
func (*ValueFilter) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *ValueFilter) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *ValueFilter) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type GeoFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopLeftLat     float64                `protobuf:"fixed64,1,opt,name=top_left_lat,json=topLeftLat,proto3" json:"top_left_lat,omitempty"`
	TopLeftLon     float64                `protobuf:"fixed64,2,opt,name=top_left_lon,json=topLeftLon,proto3" json:"top_left_lon,omitempty"`
	BottomRightLat float64                `protobuf:"fixed64,3,opt,name=bottom_right_lat,json=bottomRightLat,proto3" json:"bottom_right_lat,omitempty"`
	BottomRightLon float64                `protobuf:"fixed64,4,opt,name=bottom_right_lon,json=bottomRightLon,proto3" json:"bottom_right_lon,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GeoFilter) Reset() {
	*x = GeoFilter{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoFilter) ProtoMessage() {}

func (x *GeoFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoFilter.ProtoReflect.Descriptor instead.
func (*GeoFilter) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GeoFilter) GetTopLeftLat() float64 {
	if x != nil {
		return x.TopLeftLat
	}
	return 0
}

func (x *GeoFilter) GetTopLeftLon() float64 {
	if x != nil {
		return x.TopLeftLon
	}
	return 0
}

func (x *GeoFilter) GetBottomRightLat() float64 {
	if x != nil {
		return x.BottomRightLat
	}
	return 0
}

func (x *GeoFilter) GetBottomRightLon() float64 {
	if x != nil {
		return x.BottomRightLon
	}
	return 0
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // default 50, max 1000
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // cursor for next page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type SortOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`            // default "@timestamp"
	Descending    bool                   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"` // default true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortOrder) Reset() {
	*x = SortOrder{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortOrder) ProtoMessage() {}

func (x *SortOrder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortOrder.ProtoReflect.Descriptor instead.
func (*SortOrder) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *SortOrder) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortOrder) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type BucketSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FixedInterval string                 `protobuf:"bytes,1,opt,name=fixed_interval,json=fixedInterval,proto3" json:"fixed_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketSpec) Reset() {
	*x = BucketSpec{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSpec) ProtoMessage() {}

func (x *BucketSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSpec.ProtoReflect.Descriptor instead.
func (*BucketSpec) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *BucketSpec) GetFixedInterval() string {
	if x != nil {
		return x.FixedInterval
	}
	return ""
}

type TelemetryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceTypeId  string                 `protobuf:"bytes,6,opt,name=device_type_id,json=deviceTypeId,proto3" json:"device_type_id,omitempty"`
	SensorId      string                 `protobuf:"bytes,7,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Channel       string                 `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	CorrelationId string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Event         string                 `protobuf:"bytes,10,opt,name=event,proto3" json:"event,omitempty"`
	Type          string                 `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Value         *float64               `protobuf:"fixed64,12,opt,name=value,proto3,oneof" json:"value,omitempty"`
	ValueText     string                 `protobuf:"bytes,13,opt,name=value_text,json=valueText,proto3" json:"value_text,omitempty"`
	GeoLat        *float64               `protobuf:"fixed64,14,opt,name=geo_lat,json=geoLat,proto3,oneof" json:"geo_lat,omitempty"`
	GeoLon        *float64               `protobuf:"fixed64,15,opt,name=geo_lon,json=geoLon,proto3,oneof" json:"geo_lon,omitempty"`
	Unit          string                 `protobuf:"bytes,16,opt,name=unit,proto3" json:"unit,omitempty"`
	Name          string                 `protobuf:"bytes,17,opt,name=name,proto3" json:"name,omitempty"`
	DataType      string                 `protobuf:"bytes,18,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Remark        string                 `protobuf:"bytes,19,opt,name=remark,proto3" json:"remark,omitempty"`
	SourceId      string                 `protobuf:"bytes,20,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *TelemetryEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TelemetryEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TelemetryEvent) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *TelemetryEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TelemetryEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryEvent) GetDeviceTypeId() string {
	if x != nil {
		return x.DeviceTypeId
	}
	return ""
}

func (x *TelemetryEvent) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *TelemetryEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *TelemetryEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TelemetryEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TelemetryEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TelemetryEvent) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *TelemetryEvent) GetValueText() string {
	if x != nil {
		return x.ValueText
	}
	return ""
}

func (x *TelemetryEvent) GetGeoLat() float64 {
	if x != nil && x.GeoLat != nil {
		return *x.GeoLat
	}
	return 0
}

func (x *TelemetryEvent) GetGeoLon() float64 {
	if x != nil && x.GeoLon != nil {
		return *x.GeoLon
	}
	return 0
}

func (x *TelemetryEvent) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *TelemetryEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TelemetryEvent) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *TelemetryEvent) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TelemetryEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *TelemetryEvent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TelemetryEvent) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type SearchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *TimeRange             `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Filter        *TelemetryFilter       `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Sort          *SortOrder             `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEventsRequest) Reset() {
	*x = SearchEventsRequest{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventsRequest) ProtoMessage() {}

func (x *SearchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventsRequest.ProtoReflect.Descriptor instead.
func (*SearchEventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *SearchEventsRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *SearchEventsRequest) GetFilter() *TelemetryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchEventsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchEventsRequest) GetSort() *SortOrder {
	if x != nil {
		return x.Sort
	}
	return nil
}

type SearchEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TelemetryEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEventsResponse) Reset() {
	*x = SearchEventsResponse{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventsResponse) ProtoMessage() {}

func (x *SearchEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventsResponse.ProtoReflect.Descriptor instead.
func (*SearchEventsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *SearchEventsResponse) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SearchEventsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetTimeHistogramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *TimeRange             `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Bucket        *BucketSpec            `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"` // Use bucket.fixed_interval OR resolution (not both)
	Filter        *TelemetryFilter       `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	GroupBy       string                 `protobuf:"bytes,4,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`           // "device_id", "sensor_id", "channel", "event"
	TopN          int32                  `protobuf:"varint,5,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`                   // default 10, max 100
	MaxBuckets    int32                  `protobuf:"varint,6,opt,name=max_buckets,json=maxBuckets,proto3" json:"max_buckets,omitempty"` // default 1440
	Resolution    string                 `protobuf:"bytes,7,opt,name=resolution,proto3" json:"resolution,omitempty"`                    // Simpler alternative to bucket: "1m", "5m", "1h", "6h", "1d"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeHistogramRequest) Reset() {
	*x = GetTimeHistogramRequest{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeHistogramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeHistogramRequest) ProtoMessage() {}

func (x *GetTimeHistogramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeHistogramRequest.ProtoReflect.Descriptor instead.
func (*GetTimeHistogramRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetTimeHistogramRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *GetTimeHistogramRequest) GetBucket() *BucketSpec {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *GetTimeHistogramRequest) GetFilter() *TelemetryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetTimeHistogramRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *GetTimeHistogramRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *GetTimeHistogramRequest) GetMaxBuckets() int32 {
	if x != nil {
		return x.MaxBuckets
	}
	return 0
}

func (x *GetTimeHistogramRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

type TimeSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            string                 `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	AvgValue      *float64               `protobuf:"fixed64,3,opt,name=avg_value,json=avgValue,proto3,oneof" json:"avg_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *TimeSeriesPoint) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *TimeSeriesPoint) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TimeSeriesPoint) GetAvgValue() float64 {
	if x != nil && x.AvgValue != nil {
		return *x.AvgValue
	}
	return 0
}

type TimeSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Points        []*TimeSeriesPoint     `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeries) Reset() {
	*x = TimeSeries{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeries) ProtoMessage() {}

func (x *TimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeries.ProtoReflect.Descriptor instead.
func (*TimeSeries) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *TimeSeries) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TimeSeries) GetPoints() []*TimeSeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetTimeHistogramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*TimeSeries          `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	TotalEvents   int64                  `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeHistogramResponse) Reset() {
	*x = GetTimeHistogramResponse{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeHistogramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeHistogramResponse) ProtoMessage() {}

func (x *GetTimeHistogramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeHistogramResponse.ProtoReflect.Descriptor instead.
func (*GetTimeHistogramResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *GetTimeHistogramResponse) GetSeries() []*TimeSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *GetTimeHistogramResponse) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

type GetAggregationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *TimeRange             `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Filter        *TelemetryFilter       `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	GroupBy       []string               `protobuf:"bytes,3,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"` // "device_id", "sensor_id", "channel", "event", "type"
	Aggregations  []AggregationType      `protobuf:"varint,4,rep,packed,name=aggregations,proto3,enum=pkg.proto.telemetry.v1.AggregationType" json:"aggregations,omitempty"`
	TopN          int32                  `protobuf:"varint,5,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"` // default 20, max 1000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregationsRequest) Reset() {
	*x = GetAggregationsRequest{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregationsRequest) ProtoMessage() {}

func (x *GetAggregationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregationsRequest.ProtoReflect.Descriptor instead.
func (*GetAggregationsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *GetAggregationsRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *GetAggregationsRequest) GetFilter() *TelemetryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetAggregationsRequest) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *GetAggregationsRequest) GetAggregations() []AggregationType {
	if x != nil {
		return x.Aggregations
	}
	return nil
}

func (x *GetAggregationsRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type AggregationBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimensions    map[string]string      `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	AvgValue      *float64               `protobuf:"fixed64,3,opt,name=avg_value,json=avgValue,proto3,oneof" json:"avg_value,omitempty"`
	MinValue      *float64               `protobuf:"fixed64,4,opt,name=min_value,json=minValue,proto3,oneof" json:"min_value,omitempty"`
	MaxValue      *float64               `protobuf:"fixed64,5,opt,name=max_value,json=maxValue,proto3,oneof" json:"max_value,omitempty"`
	SumValue      *float64               `protobuf:"fixed64,6,opt,name=sum_value,json=sumValue,proto3,oneof" json:"sum_value,omitempty"`
	UniqueCount   *int64                 `protobuf:"varint,7,opt,name=unique_count,json=uniqueCount,proto3,oneof" json:"unique_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationBucket) Reset() {
	*x = AggregationBucket{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationBucket) ProtoMessage() {}

func (x *AggregationBucket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationBucket.ProtoReflect.Descriptor instead.
func (*AggregationBucket) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *AggregationBucket) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *AggregationBucket) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregationBucket) GetAvgValue() float64 {
	if x != nil && x.AvgValue != nil {
		return *x.AvgValue
	}
	return 0
}

func (x *AggregationBucket) GetMinValue() float64 {
	if x != nil && x.MinValue != nil {
		return *x.MinValue
	}
	return 0
}

func (x *AggregationBucket) GetMaxValue() float64 {
	if x != nil && x.MaxValue != nil {
		return *x.MaxValue
	}
	return 0
}

func (x *AggregationBucket) GetSumValue() float64 {
	if x != nil && x.SumValue != nil {
		return *x.SumValue
	}
	return 0
}

func (x *AggregationBucket) GetUniqueCount() int64 {
	if x != nil && x.UniqueCount != nil {
		return *x.UniqueCount
	}
	return 0
}

type GetAggregationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*AggregationBucket   `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	TotalBuckets  int64                  `protobuf:"varint,2,opt,name=total_buckets,json=totalBuckets,proto3" json:"total_buckets,omitempty"`
	OtherBuckets  int64                  `protobuf:"varint,3,opt,name=other_buckets,json=otherBuckets,proto3" json:"other_buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregationsResponse) Reset() {
	*x = GetAggregationsResponse{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregationsResponse) ProtoMessage() {}

func (x *GetAggregationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregationsResponse.ProtoReflect.Descriptor instead.
func (*GetAggregationsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *GetAggregationsResponse) GetBuckets() []*AggregationBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *GetAggregationsResponse) GetTotalBuckets() int64 {
	if x != nil {
		return x.TotalBuckets
	}
	return 0
}

func (x *GetAggregationsResponse) GetOtherBuckets() int64 {
	if x != nil {
		return x.OtherBuckets
	}
	return 0
}

type GetLatestEventsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Filter          *TelemetryFilter       `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                           // default 10, max 100
	TimeDescription string                 `protobuf:"bytes,3,opt,name=time_description,json=timeDescription,proto3" json:"time_description,omitempty"` // "last hour", "today", "yesterday"
	Range           *TimeRange             `protobuf:"bytes,4,opt,name=range,proto3" json:"range,omitempty"`                                            // fallback if time_description not provided
	IncludeSummary  bool                   `protobuf:"varint,5,opt,name=include_summary,json=includeSummary,proto3" json:"include_summary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLatestEventsRequest) Reset() {
	*x = GetLatestEventsRequest{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestEventsRequest) ProtoMessage() {}

func (x *GetLatestEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestEventsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestEventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *GetLatestEventsRequest) GetFilter() *TelemetryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetLatestEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLatestEventsRequest) GetTimeDescription() string {
	if x != nil {
		return x.TimeDescription
	}
	return ""
}

func (x *GetLatestEventsRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *GetLatestEventsRequest) GetIncludeSummary() bool {
	if x != nil {
		return x.IncludeSummary
	}
	return false
}

type GetLatestEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TelemetryEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalInRange  int64                  `protobuf:"varint,2,opt,name=total_in_range,json=totalInRange,proto3" json:"total_in_range,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"` // "Found 156 events from 3 devices..."
	ParsedStart   string                 `protobuf:"bytes,4,opt,name=parsed_start,json=parsedStart,proto3" json:"parsed_start,omitempty"`
	ParsedEnd     string                 `protobuf:"bytes,5,opt,name=parsed_end,json=parsedEnd,proto3" json:"parsed_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestEventsResponse) Reset() {
	*x = GetLatestEventsResponse{}
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestEventsResponse) ProtoMessage() {}

func (x *GetLatestEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestEventsResponse.ProtoReflect.Descriptor instead.
func (*GetLatestEventsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *GetLatestEventsResponse) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetLatestEventsResponse) GetTotalInRange() int64 {
	if x != nil {
		return x.TotalInRange
	}
	return 0
}

func (x *GetLatestEventsResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GetLatestEventsResponse) GetParsedStart() string {
	if x != nil {
		return x.ParsedStart
	}
	return ""
}

func (x *GetLatestEventsResponse) GetParsedEnd() string {
	if x != nil {
		return x.ParsedEnd
	}
	return ""
}

var File_pkg_proto_telemetry_v1_telemetry_analytics_proto protoreflect.FileDescriptor

const file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDesc = "" +
	"\n" +
	"0pkg/proto/telemetry/v1/telemetry_analytics.proto\x12\x16pkg.proto.telemetry.v1\"a\n" +
	"\tTimeRange\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"\xc0\x03\n" +
	"\x0fTelemetryFilter\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12$\n" +
	"\x0edevice_type_id\x18\x04 \x01(\tR\fdeviceTypeId\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x05 \x03(\tR\tsensorIds\x12\x1a\n" +
	"\bchannels\x18\x06 \x03(\tR\bchannels\x12\x1f\n" +
	"\vevent_types\x18\a \x03(\tR\n" +
	"eventTypes\x12\x1d\n" +
	"\n" +
	"data_types\x18\b \x03(\tR\tdataTypes\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x12F\n" +
	"\fvalue_filter\x18\n" +
	" \x01(\v2#.pkg.proto.telemetry.v1.ValueFilterR\vvalueFilter\x12@\n" +
	"\n" +
	"geo_filter\x18\v \x01(\v2!.pkg.proto.telemetry.v1.GeoFilterR\tgeoFilter\"K\n" +
	"\vValueFilter\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x01H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x01H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"\xa3\x01\n" +
	"\tGeoFilter\x12 \n" +
	"\ftop_left_lat\x18\x01 \x01(\x01R\n" +
	"topLeftLat\x12 \n" +
	"\ftop_left_lon\x18\x02 \x01(\x01R\n" +
	"topLeftLon\x12(\n" +
	"\x10bottom_right_lat\x18\x03 \x01(\x01R\x0ebottomRightLat\x12(\n" +
	"\x10bottom_right_lon\x18\x04 \x01(\x01R\x0ebottomRightLon\"H\n" +
	"\n" +
	"Pagination\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"A\n" +
	"\tSortOrder\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1e\n" +
	"\n" +
	"descending\x18\x02 \x01(\bR\n" +
	"descending\"3\n" +
	"\n" +
	"BucketSpec\x12%\n" +
	"\x0efixed_interval\x18\x01 \x01(\tR\rfixedInterval\"\x99\x05\n" +
	"\x0eTelemetryEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12$\n" +
	"\x0edevice_type_id\x18\x06 \x01(\tR\fdeviceTypeId\x12\x1b\n" +
	"\tsensor_id\x18\a \x01(\tR\bsensorId\x12\x18\n" +
	"\achannel\x18\b \x01(\tR\achannel\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x12\x14\n" +
	"\x05event\x18\n" +
	" \x01(\tR\x05event\x12\x12\n" +
	"\x04type\x18\v \x01(\tR\x04type\x12\x19\n" +
	"\x05value\x18\f \x01(\x01H\x00R\x05value\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"value_text\x18\r \x01(\tR\tvalueText\x12\x1c\n" +
	"\ageo_lat\x18\x0e \x01(\x01H\x01R\x06geoLat\x88\x01\x01\x12\x1c\n" +
	"\ageo_lon\x18\x0f \x01(\x01H\x02R\x06geoLon\x88\x01\x01\x12\x12\n" +
	"\x04unit\x18\x10 \x01(\tR\x04unit\x12\x12\n" +
	"\x04name\x18\x11 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x12 \x01(\tR\bdataType\x12\x16\n" +
	"\x06remark\x18\x13 \x01(\tR\x06remark\x12\x1b\n" +
	"\tsource_id\x18\x14 \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x15 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\x03R\tupdatedAtB\b\n" +
	"\x06_valueB\n" +
	"\n" +
	"\b_geo_latB\n" +
	"\n" +
	"\b_geo_lon\"\x8a\x02\n" +
	"\x13SearchEventsRequest\x127\n" +
	"\x05range\x18\x01 \x01(\v2!.pkg.proto.telemetry.v1.TimeRangeR\x05range\x12?\n" +
	"\x06filter\x18\x02 \x01(\v2'.pkg.proto.telemetry.v1.TelemetryFilterR\x06filter\x12B\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\".pkg.proto.telemetry.v1.PaginationR\n" +
	"pagination\x125\n" +
	"\x04sort\x18\x04 \x01(\v2!.pkg.proto.telemetry.v1.SortOrderR\x04sort\"\x9f\x01\n" +
	"\x14SearchEventsResponse\x12>\n" +
	"\x06events\x18\x01 \x03(\v2&.pkg.proto.telemetry.v1.TelemetryEventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"\xc0\x02\n" +
	"\x17GetTimeHistogramRequest\x127\n" +
	"\x05range\x18\x01 \x01(\v2!.pkg.proto.telemetry.v1.TimeRangeR\x05range\x12:\n" +
	"\x06bucket\x18\x02 \x01(\v2\".pkg.proto.telemetry.v1.BucketSpecR\x06bucket\x12?\n" +
	"\x06filter\x18\x03 \x01(\v2'.pkg.proto.telemetry.v1.TelemetryFilterR\x06filter\x12\x19\n" +
	"\bgroup_by\x18\x04 \x01(\tR\agroupBy\x12\x13\n" +
	"\x05top_n\x18\x05 \x01(\x05R\x04topN\x12\x1f\n" +
	"\vmax_buckets\x18\x06 \x01(\x05R\n" +
	"maxBuckets\x12\x1e\n" +
	"\n" +
	"resolution\x18\a \x01(\tR\n" +
	"resolution\"g\n" +
	"\x0fTimeSeriesPoint\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\tR\x02ts\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12 \n" +
	"\tavg_value\x18\x03 \x01(\x01H\x00R\bavgValue\x88\x01\x01B\f\n" +
	"\n" +
	"_avg_value\"_\n" +
	"\n" +
	"TimeSeries\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12?\n" +
	"\x06points\x18\x02 \x03(\v2'.pkg.proto.telemetry.v1.TimeSeriesPointR\x06points\"y\n" +
	"\x18GetTimeHistogramResponse\x12:\n" +
	"\x06series\x18\x01 \x03(\v2\".pkg.proto.telemetry.v1.TimeSeriesR\x06series\x12!\n" +
	"\ftotal_events\x18\x02 \x01(\x03R\vtotalEvents\"\x8f\x02\n" +
	"\x16GetAggregationsRequest\x127\n" +
	"\x05range\x18\x01 \x01(\v2!.pkg.proto.telemetry.v1.TimeRangeR\x05range\x12?\n" +
	"\x06filter\x18\x02 \x01(\v2'.pkg.proto.telemetry.v1.TelemetryFilterR\x06filter\x12\x19\n" +
	"\bgroup_by\x18\x03 \x03(\tR\agroupBy\x12K\n" +
	"\faggregations\x18\x04 \x03(\x0e2'.pkg.proto.telemetry.v1.AggregationTypeR\faggregations\x12\x13\n" +
	"\x05top_n\x18\x05 \x01(\x05R\x04topN\"\xbc\x03\n" +
	"\x11AggregationBucket\x12Y\n" +
	"\n" +
	"dimensions\x18\x01 \x03(\v29.pkg.proto.telemetry.v1.AggregationBucket.DimensionsEntryR\n" +
	"dimensions\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12 \n" +
	"\tavg_value\x18\x03 \x01(\x01H\x00R\bavgValue\x88\x01\x01\x12 \n" +
	"\tmin_value\x18\x04 \x01(\x01H\x01R\bminValue\x88\x01\x01\x12 \n" +
	"\tmax_value\x18\x05 \x01(\x01H\x02R\bmaxValue\x88\x01\x01\x12 \n" +
	"\tsum_value\x18\x06 \x01(\x01H\x03R\bsumValue\x88\x01\x01\x12&\n" +
	"\funique_count\x18\a \x01(\x03H\x04R\vuniqueCount\x88\x01\x01\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_avg_valueB\f\n" +
	"\n" +
	"_min_valueB\f\n" +
	"\n" +
	"_max_valueB\f\n" +
	"\n" +
	"_sum_valueB\x0f\n" +
	"\r_unique_count\"\xa8\x01\n" +
	"\x17GetAggregationsResponse\x12C\n" +
	"\abuckets\x18\x01 \x03(\v2).pkg.proto.telemetry.v1.AggregationBucketR\abuckets\x12#\n" +
	"\rtotal_buckets\x18\x02 \x01(\x03R\ftotalBuckets\x12#\n" +
	"\rother_buckets\x18\x03 \x01(\x03R\fotherBuckets\"\xfc\x01\n" +
	"\x16GetLatestEventsRequest\x12?\n" +
	"\x06filter\x18\x01 \x01(\v2'.pkg.proto.telemetry.v1.TelemetryFilterR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12)\n" +
	"\x10time_description\x18\x03 \x01(\tR\x0ftimeDescription\x127\n" +
	"\x05range\x18\x04 \x01(\v2!.pkg.proto.telemetry.v1.TimeRangeR\x05range\x12'\n" +
	"\x0finclude_summary\x18\x05 \x01(\bR\x0eincludeSummary\"\xdb\x01\n" +
	"\x17GetLatestEventsResponse\x12>\n" +
	"\x06events\x18\x01 \x03(\v2&.pkg.proto.telemetry.v1.TelemetryEventR\x06events\x12$\n" +
	"\x0etotal_in_range\x18\x02 \x01(\x03R\ftotalInRange\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12!\n" +
	"\fparsed_start\x18\x04 \x01(\tR\vparsedStart\x12\x1d\n" +
	"\n" +
	"parsed_end\x18\x05 \x01(\tR\tparsedEnd*\xd9\x01\n" +
	"\x0fAggregationType\x12 \n" +
	"\x1cAGGREGATION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16AGGREGATION_TYPE_COUNT\x10\x01\x12\x18\n" +
	"\x14AGGREGATION_TYPE_AVG\x10\x02\x12\x18\n" +
	"\x14AGGREGATION_TYPE_MIN\x10\x03\x12\x18\n" +
	"\x14AGGREGATION_TYPE_MAX\x10\x04\x12\x18\n" +
	"\x14AGGREGATION_TYPE_SUM\x10\x05\x12 \n" +
	"\x1cAGGREGATION_TYPE_CARDINALITY\x10\x062\xde\x03\n" +
	"\x12TelemetryAnalytics\x12i\n" +
	"\fSearchEvents\x12+.pkg.proto.telemetry.v1.SearchEventsRequest\x1a,.pkg.proto.telemetry.v1.SearchEventsResponse\x12u\n" +
	"\x10GetTimeHistogram\x12/.pkg.proto.telemetry.v1.GetTimeHistogramRequest\x1a0.pkg.proto.telemetry.v1.GetTimeHistogramResponse\x12r\n" +
	"\x0fGetAggregations\x12..pkg.proto.telemetry.v1.GetAggregationsRequest\x1a/.pkg.proto.telemetry.v1.GetAggregationsResponse\x12r\n" +
	"\x0fGetLatestEvents\x12..pkg.proto.telemetry.v1.GetLatestEventsRequest\x1a/.pkg.proto.telemetry.v1.GetLatestEventsResponseBAZ?github.com/myDevicesIoT/protos/pkg/proto/telemetry/v1;telemetryb\x06proto3"

var (
	file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescOnce sync.Once
	file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescData []byte
)

func file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescGZIP() []byte {
	file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescOnce.Do(func() {
		file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDesc), len(file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDesc)))
	})
	return file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDescData
}

var file_pkg_proto_telemetry_v1_telemetry_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_proto_telemetry_v1_telemetry_analytics_proto_goTypes = []any{
	(AggregationType)(0),             // 0: pkg.proto.telemetry.v1.AggregationType
	(*TimeRange)(nil),                // 1: pkg.proto.telemetry.v1.TimeRange
	(*TelemetryFilter)(nil),          // 2: pkg.proto.telemetry.v1.TelemetryFilter
	(*ValueFilter)(nil),              // 3: pkg.proto.telemetry.v1.ValueFilter
	(*GeoFilter)(nil),                // 4: pkg.proto.telemetry.v1.GeoFilter
	(*Pagination)(nil),               // 5: pkg.proto.telemetry.v1.Pagination
	(*SortOrder)(nil),                // 6: pkg.proto.telemetry.v1.SortOrder
	(*BucketSpec)(nil),               // 7: pkg.proto.telemetry.v1.BucketSpec
	(*TelemetryEvent)(nil),           // 8: pkg.proto.telemetry.v1.TelemetryEvent
	(*SearchEventsRequest)(nil),      // 9: pkg.proto.telemetry.v1.SearchEventsRequest
	(*SearchEventsResponse)(nil),     // 10: pkg.proto.telemetry.v1.SearchEventsResponse
	(*GetTimeHistogramRequest)(nil),  // 11: pkg.proto.telemetry.v1.GetTimeHistogramRequest
	(*TimeSeriesPoint)(nil),          // 12: pkg.proto.telemetry.v1.TimeSeriesPoint
	(*TimeSeries)(nil),               // 13: pkg.proto.telemetry.v1.TimeSeries
	(*GetTimeHistogramResponse)(nil), // 14: pkg.proto.telemetry.v1.GetTimeHistogramResponse
	(*GetAggregationsRequest)(nil),   // 15: pkg.proto.telemetry.v1.GetAggregationsRequest
	(*AggregationBucket)(nil),        // 16: pkg.proto.telemetry.v1.AggregationBucket
	(*GetAggregationsResponse)(nil),  // 17: pkg.proto.telemetry.v1.GetAggregationsResponse
	(*GetLatestEventsRequest)(nil),   // 18: pkg.proto.telemetry.v1.GetLatestEventsRequest
	(*GetLatestEventsResponse)(nil),  // 19: pkg.proto.telemetry.v1.GetLatestEventsResponse
	nil,                              // 20: pkg.proto.telemetry.v1.AggregationBucket.DimensionsEntry
}
var file_pkg_proto_telemetry_v1_telemetry_analytics_proto_depIdxs = []int32{
	3,  // 0: pkg.proto.telemetry.v1.TelemetryFilter.value_filter:type_name -> pkg.proto.telemetry.v1.ValueFilter
	4,  // 1: pkg.proto.telemetry.v1.TelemetryFilter.geo_filter:type_name -> pkg.proto.telemetry.v1.GeoFilter
	1,  // 2: pkg.proto.telemetry.v1.SearchEventsRequest.range:type_name -> pkg.proto.telemetry.v1.TimeRange
	2,  // 3: pkg.proto.telemetry.v1.SearchEventsRequest.filter:type_name -> pkg.proto.telemetry.v1.TelemetryFilter
	5,  // 4: pkg.proto.telemetry.v1.SearchEventsRequest.pagination:type_name -> pkg.proto.telemetry.v1.Pagination
	6,  // 5: pkg.proto.telemetry.v1.SearchEventsRequest.sort:type_name -> pkg.proto.telemetry.v1.SortOrder
	8,  // 6: pkg.proto.telemetry.v1.SearchEventsResponse.events:type_name -> pkg.proto.telemetry.v1.TelemetryEvent
	1,  // 7: pkg.proto.telemetry.v1.GetTimeHistogramRequest.range:type_name -> pkg.proto.telemetry.v1.TimeRange
	7,  // 8: pkg.proto.telemetry.v1.GetTimeHistogramRequest.bucket:type_name -> pkg.proto.telemetry.v1.BucketSpec
	2,  // 9: pkg.proto.telemetry.v1.GetTimeHistogramRequest.filter:type_name -> pkg.proto.telemetry.v1.TelemetryFilter
	12, // 10: pkg.proto.telemetry.v1.TimeSeries.points:type_name -> pkg.proto.telemetry.v1.TimeSeriesPoint
	13, // 11: pkg.proto.telemetry.v1.GetTimeHistogramResponse.series:type_name -> pkg.proto.telemetry.v1.TimeSeries
	1,  // 12: pkg.proto.telemetry.v1.GetAggregationsRequest.range:type_name -> pkg.proto.telemetry.v1.TimeRange
	2,  // 13: pkg.proto.telemetry.v1.GetAggregationsRequest.filter:type_name -> pkg.proto.telemetry.v1.TelemetryFilter
	0,  // 14: pkg.proto.telemetry.v1.GetAggregationsRequest.aggregations:type_name -> pkg.proto.telemetry.v1.AggregationType
	20, // 15: pkg.proto.telemetry.v1.AggregationBucket.dimensions:type_name -> pkg.proto.telemetry.v1.AggregationBucket.DimensionsEntry
	16, // 16: pkg.proto.telemetry.v1.GetAggregationsResponse.buckets:type_name -> pkg.proto.telemetry.v1.AggregationBucket
	2,  // 17: pkg.proto.telemetry.v1.GetLatestEventsRequest.filter:type_name -> pkg.proto.telemetry.v1.TelemetryFilter
	1,  // 18: pkg.proto.telemetry.v1.GetLatestEventsRequest.range:type_name -> pkg.proto.telemetry.v1.TimeRange
	8,  // 19: pkg.proto.telemetry.v1.GetLatestEventsResponse.events:type_name -> pkg.proto.telemetry.v1.TelemetryEvent
	9,  // 20: pkg.proto.telemetry.v1.TelemetryAnalytics.SearchEvents:input_type -> pkg.proto.telemetry.v1.SearchEventsRequest
	11, // 21: pkg.proto.telemetry.v1.TelemetryAnalytics.GetTimeHistogram:input_type -> pkg.proto.telemetry.v1.GetTimeHistogramRequest
	15, // 22: pkg.proto.telemetry.v1.TelemetryAnalytics.GetAggregations:input_type -> pkg.proto.telemetry.v1.GetAggregationsRequest
	18, // 23: pkg.proto.telemetry.v1.TelemetryAnalytics.GetLatestEvents:input_type -> pkg.proto.telemetry.v1.GetLatestEventsRequest
	10, // 24: pkg.proto.telemetry.v1.TelemetryAnalytics.SearchEvents:output_type -> pkg.proto.telemetry.v1.SearchEventsResponse
	14, // 25: pkg.proto.telemetry.v1.TelemetryAnalytics.GetTimeHistogram:output_type -> pkg.proto.telemetry.v1.GetTimeHistogramResponse
	17, // 26: pkg.proto.telemetry.v1.TelemetryAnalytics.GetAggregations:output_type -> pkg.proto.telemetry.v1.GetAggregationsResponse
	19, // 27: pkg.proto.telemetry.v1.TelemetryAnalytics.GetLatestEvents:output_type -> pkg.proto.telemetry.v1.GetLatestEventsResponse
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_proto_telemetry_v1_telemetry_analytics_proto_init() }
func file_pkg_proto_telemetry_v1_telemetry_analytics_proto_init() {
	if File_pkg_proto_telemetry_v1_telemetry_analytics_proto != nil {
		return
	}
	file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[2].OneofWrappers = []any{}
	file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[7].OneofWrappers = []any{}
	file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[11].OneofWrappers = []any{}
	file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDesc), len(file_pkg_proto_telemetry_v1_telemetry_analytics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_telemetry_v1_telemetry_analytics_proto_goTypes,
		DependencyIndexes: file_pkg_proto_telemetry_v1_telemetry_analytics_proto_depIdxs,
		EnumInfos:         file_pkg_proto_telemetry_v1_telemetry_analytics_proto_enumTypes,
		MessageInfos:      file_pkg_proto_telemetry_v1_telemetry_analytics_proto_msgTypes,
	}.Build()
	File_pkg_proto_telemetry_v1_telemetry_analytics_proto = out.File
	file_pkg_proto_telemetry_v1_telemetry_analytics_proto_goTypes = nil
	file_pkg_proto_telemetry_v1_telemetry_analytics_proto_depIdxs = nil
}
