// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: pkg/proto/telemetry/v1/telemetry_analytics.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryAnalytics_SearchEvents_FullMethodName     = "/pkg.proto.telemetry.v1.TelemetryAnalytics/SearchEvents"
	TelemetryAnalytics_GetTimeHistogram_FullMethodName = "/pkg.proto.telemetry.v1.TelemetryAnalytics/GetTimeHistogram"
	TelemetryAnalytics_GetAggregations_FullMethodName  = "/pkg.proto.telemetry.v1.TelemetryAnalytics/GetAggregations"
	TelemetryAnalytics_GetLatestEvents_FullMethodName  = "/pkg.proto.telemetry.v1.TelemetryAnalytics/GetLatestEvents"
)

// TelemetryAnalyticsClient is the client API for TelemetryAnalytics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryAnalyticsClient interface {
	SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
	GetTimeHistogram(ctx context.Context, in *GetTimeHistogramRequest, opts ...grpc.CallOption) (*GetTimeHistogramResponse, error)
	GetAggregations(ctx context.Context, in *GetAggregationsRequest, opts ...grpc.CallOption) (*GetAggregationsResponse, error)
	GetLatestEvents(ctx context.Context, in *GetLatestEventsRequest, opts ...grpc.CallOption) (*GetLatestEventsResponse, error)
}

type telemetryAnalyticsClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryAnalyticsClient(cc grpc.ClientConnInterface) TelemetryAnalyticsClient {
	return &telemetryAnalyticsClient{cc}
}

func (c *telemetryAnalyticsClient) SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, TelemetryAnalytics_SearchEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryAnalyticsClient) GetTimeHistogram(ctx context.Context, in *GetTimeHistogramRequest, opts ...grpc.CallOption) (*GetTimeHistogramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimeHistogramResponse)
	err := c.cc.Invoke(ctx, TelemetryAnalytics_GetTimeHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryAnalyticsClient) GetAggregations(ctx context.Context, in *GetAggregationsRequest, opts ...grpc.CallOption) (*GetAggregationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAggregationsResponse)
	err := c.cc.Invoke(ctx, TelemetryAnalytics_GetAggregations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryAnalyticsClient) GetLatestEvents(ctx context.Context, in *GetLatestEventsRequest, opts ...grpc.CallOption) (*GetLatestEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestEventsResponse)
	err := c.cc.Invoke(ctx, TelemetryAnalytics_GetLatestEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryAnalyticsServer is the server API for TelemetryAnalytics service.
// All implementations should embed UnimplementedTelemetryAnalyticsServer
// for forward compatibility.
type TelemetryAnalyticsServer interface {
	SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error)
	GetTimeHistogram(context.Context, *GetTimeHistogramRequest) (*GetTimeHistogramResponse, error)
	GetAggregations(context.Context, *GetAggregationsRequest) (*GetAggregationsResponse, error)
	GetLatestEvents(context.Context, *GetLatestEventsRequest) (*GetLatestEventsResponse, error)
}

// UnimplementedTelemetryAnalyticsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryAnalyticsServer struct{}

func (UnimplementedTelemetryAnalyticsServer) SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchEvents not implemented")
}
func (UnimplementedTelemetryAnalyticsServer) GetTimeHistogram(context.Context, *GetTimeHistogramRequest) (*GetTimeHistogramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeHistogram not implemented")
}
func (UnimplementedTelemetryAnalyticsServer) GetAggregations(context.Context, *GetAggregationsRequest) (*GetAggregationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAggregations not implemented")
}
func (UnimplementedTelemetryAnalyticsServer) GetLatestEvents(context.Context, *GetLatestEventsRequest) (*GetLatestEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestEvents not implemented")
}
func (UnimplementedTelemetryAnalyticsServer) testEmbeddedByValue() {}

// UnsafeTelemetryAnalyticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryAnalyticsServer will
// result in compilation errors.
type UnsafeTelemetryAnalyticsServer interface {
	mustEmbedUnimplementedTelemetryAnalyticsServer()
}

func RegisterTelemetryAnalyticsServer(s grpc.ServiceRegistrar, srv TelemetryAnalyticsServer) {
	// If the following call pancis, it indicates UnimplementedTelemetryAnalyticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryAnalytics_ServiceDesc, srv)
}

func _TelemetryAnalytics_SearchEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAnalyticsServer).SearchEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryAnalytics_SearchEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAnalyticsServer).SearchEvents(ctx, req.(*SearchEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryAnalytics_GetTimeHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAnalyticsServer).GetTimeHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryAnalytics_GetTimeHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAnalyticsServer).GetTimeHistogram(ctx, req.(*GetTimeHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryAnalytics_GetAggregations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAggregationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAnalyticsServer).GetAggregations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryAnalytics_GetAggregations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAnalyticsServer).GetAggregations(ctx, req.(*GetAggregationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryAnalytics_GetLatestEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAnalyticsServer).GetLatestEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryAnalytics_GetLatestEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAnalyticsServer).GetLatestEvents(ctx, req.(*GetLatestEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryAnalytics_ServiceDesc is the grpc.ServiceDesc for TelemetryAnalytics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryAnalytics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.proto.telemetry.v1.TelemetryAnalytics",
	HandlerType: (*TelemetryAnalyticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchEvents",
			Handler:    _TelemetryAnalytics_SearchEvents_Handler,
		},
		{
			MethodName: "GetTimeHistogram",
			Handler:    _TelemetryAnalytics_GetTimeHistogram_Handler,
		},
		{
			MethodName: "GetAggregations",
			Handler:    _TelemetryAnalytics_GetAggregations_Handler,
		},
		{
			MethodName: "GetLatestEvents",
			Handler:    _TelemetryAnalytics_GetLatestEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/telemetry/v1/telemetry_analytics.proto",
}
