// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/proto/telemetry/v2/device_telemetry.proto

package telemetryconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/myDevicesIoT/protos/pkg/proto/telemetry/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DeviceTelemetryName is the fully-qualified name of the DeviceTelemetry service.
	DeviceTelemetryName = "pkg.proto.telemetry.v2.DeviceTelemetry"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeviceTelemetryGetDeviceStatesProcedure is the fully-qualified name of the DeviceTelemetry's
	// GetDeviceStates RPC.
	DeviceTelemetryGetDeviceStatesProcedure = "/pkg.proto.telemetry.v2.DeviceTelemetry/GetDeviceStates"
	// DeviceTelemetryListReadingsProcedure is the fully-qualified name of the DeviceTelemetry's
	// ListReadings RPC.
	DeviceTelemetryListReadingsProcedure = "/pkg.proto.telemetry.v2.DeviceTelemetry/ListReadings"
	// DeviceTelemetryGetSeriesProcedure is the fully-qualified name of the DeviceTelemetry's GetSeries
	// RPC.
	DeviceTelemetryGetSeriesProcedure = "/pkg.proto.telemetry.v2.DeviceTelemetry/GetSeries"
	// DeviceTelemetryGetSummariesProcedure is the fully-qualified name of the DeviceTelemetry's
	// GetSummaries RPC.
	DeviceTelemetryGetSummariesProcedure = "/pkg.proto.telemetry.v2.DeviceTelemetry/GetSummaries"
	// DeviceTelemetryExportReadingsProcedure is the fully-qualified name of the DeviceTelemetry's
	// ExportReadings RPC.
	DeviceTelemetryExportReadingsProcedure = "/pkg.proto.telemetry.v2.DeviceTelemetry/ExportReadings"
)

// DeviceTelemetryClient is a client for the pkg.proto.telemetry.v2.DeviceTelemetry service.
type DeviceTelemetryClient interface {
	GetDeviceStates(context.Context, *connect.Request[v2.GetDeviceStatesRequest]) (*connect.Response[v2.GetDeviceStatesResponse], error)
	ListReadings(context.Context, *connect.Request[v2.ListReadingsRequest]) (*connect.Response[v2.ListReadingsResponse], error)
	GetSeries(context.Context, *connect.Request[v2.GetSeriesRequest]) (*connect.Response[v2.GetSeriesResponse], error)
	GetSummaries(context.Context, *connect.Request[v2.GetSummariesRequest]) (*connect.Response[v2.GetSummariesResponse], error)
	ExportReadings(context.Context, *connect.Request[v2.ExportReadingsRequest]) (*connect.Response[v2.ExportReadingsResponse], error)
}

// NewDeviceTelemetryClient constructs a client for the pkg.proto.telemetry.v2.DeviceTelemetry
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeviceTelemetryClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeviceTelemetryClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deviceTelemetryMethods := v2.File_pkg_proto_telemetry_v2_device_telemetry_proto.Services().ByName("DeviceTelemetry").Methods()
	return &deviceTelemetryClient{
		getDeviceStates: connect.NewClient[v2.GetDeviceStatesRequest, v2.GetDeviceStatesResponse](
			httpClient,
			baseURL+DeviceTelemetryGetDeviceStatesProcedure,
			connect.WithSchema(deviceTelemetryMethods.ByName("GetDeviceStates")),
			connect.WithClientOptions(opts...),
		),
		listReadings: connect.NewClient[v2.ListReadingsRequest, v2.ListReadingsResponse](
			httpClient,
			baseURL+DeviceTelemetryListReadingsProcedure,
			connect.WithSchema(deviceTelemetryMethods.ByName("ListReadings")),
			connect.WithClientOptions(opts...),
		),
		getSeries: connect.NewClient[v2.GetSeriesRequest, v2.GetSeriesResponse](
			httpClient,
			baseURL+DeviceTelemetryGetSeriesProcedure,
			connect.WithSchema(deviceTelemetryMethods.ByName("GetSeries")),
			connect.WithClientOptions(opts...),
		),
		getSummaries: connect.NewClient[v2.GetSummariesRequest, v2.GetSummariesResponse](
			httpClient,
			baseURL+DeviceTelemetryGetSummariesProcedure,
			connect.WithSchema(deviceTelemetryMethods.ByName("GetSummaries")),
			connect.WithClientOptions(opts...),
		),
		exportReadings: connect.NewClient[v2.ExportReadingsRequest, v2.ExportReadingsResponse](
			httpClient,
			baseURL+DeviceTelemetryExportReadingsProcedure,
			connect.WithSchema(deviceTelemetryMethods.ByName("ExportReadings")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deviceTelemetryClient implements DeviceTelemetryClient.
type deviceTelemetryClient struct {
	getDeviceStates *connect.Client[v2.GetDeviceStatesRequest, v2.GetDeviceStatesResponse]
	listReadings    *connect.Client[v2.ListReadingsRequest, v2.ListReadingsResponse]
	getSeries       *connect.Client[v2.GetSeriesRequest, v2.GetSeriesResponse]
	getSummaries    *connect.Client[v2.GetSummariesRequest, v2.GetSummariesResponse]
	exportReadings  *connect.Client[v2.ExportReadingsRequest, v2.ExportReadingsResponse]
}

// GetDeviceStates calls pkg.proto.telemetry.v2.DeviceTelemetry.GetDeviceStates.
func (c *deviceTelemetryClient) GetDeviceStates(ctx context.Context, req *connect.Request[v2.GetDeviceStatesRequest]) (*connect.Response[v2.GetDeviceStatesResponse], error) {
	return c.getDeviceStates.CallUnary(ctx, req)
}

// ListReadings calls pkg.proto.telemetry.v2.DeviceTelemetry.ListReadings.
func (c *deviceTelemetryClient) ListReadings(ctx context.Context, req *connect.Request[v2.ListReadingsRequest]) (*connect.Response[v2.ListReadingsResponse], error) {
	return c.listReadings.CallUnary(ctx, req)
}

// GetSeries calls pkg.proto.telemetry.v2.DeviceTelemetry.GetSeries.
func (c *deviceTelemetryClient) GetSeries(ctx context.Context, req *connect.Request[v2.GetSeriesRequest]) (*connect.Response[v2.GetSeriesResponse], error) {
	return c.getSeries.CallUnary(ctx, req)
}

// GetSummaries calls pkg.proto.telemetry.v2.DeviceTelemetry.GetSummaries.
func (c *deviceTelemetryClient) GetSummaries(ctx context.Context, req *connect.Request[v2.GetSummariesRequest]) (*connect.Response[v2.GetSummariesResponse], error) {
	return c.getSummaries.CallUnary(ctx, req)
}

// ExportReadings calls pkg.proto.telemetry.v2.DeviceTelemetry.ExportReadings.
func (c *deviceTelemetryClient) ExportReadings(ctx context.Context, req *connect.Request[v2.ExportReadingsRequest]) (*connect.Response[v2.ExportReadingsResponse], error) {
	return c.exportReadings.CallUnary(ctx, req)
}

// DeviceTelemetryHandler is an implementation of the pkg.proto.telemetry.v2.DeviceTelemetry
// service.
type DeviceTelemetryHandler interface {
	GetDeviceStates(context.Context, *connect.Request[v2.GetDeviceStatesRequest]) (*connect.Response[v2.GetDeviceStatesResponse], error)
	ListReadings(context.Context, *connect.Request[v2.ListReadingsRequest]) (*connect.Response[v2.ListReadingsResponse], error)
	GetSeries(context.Context, *connect.Request[v2.GetSeriesRequest]) (*connect.Response[v2.GetSeriesResponse], error)
	GetSummaries(context.Context, *connect.Request[v2.GetSummariesRequest]) (*connect.Response[v2.GetSummariesResponse], error)
	ExportReadings(context.Context, *connect.Request[v2.ExportReadingsRequest]) (*connect.Response[v2.ExportReadingsResponse], error)
}

// NewDeviceTelemetryHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeviceTelemetryHandler(svc DeviceTelemetryHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deviceTelemetryMethods := v2.File_pkg_proto_telemetry_v2_device_telemetry_proto.Services().ByName("DeviceTelemetry").Methods()
	deviceTelemetryGetDeviceStatesHandler := connect.NewUnaryHandler(
		DeviceTelemetryGetDeviceStatesProcedure,
		svc.GetDeviceStates,
		connect.WithSchema(deviceTelemetryMethods.ByName("GetDeviceStates")),
		connect.WithHandlerOptions(opts...),
	)
	deviceTelemetryListReadingsHandler := connect.NewUnaryHandler(
		DeviceTelemetryListReadingsProcedure,
		svc.ListReadings,
		connect.WithSchema(deviceTelemetryMethods.ByName("ListReadings")),
		connect.WithHandlerOptions(opts...),
	)
	deviceTelemetryGetSeriesHandler := connect.NewUnaryHandler(
		DeviceTelemetryGetSeriesProcedure,
		svc.GetSeries,
		connect.WithSchema(deviceTelemetryMethods.ByName("GetSeries")),
		connect.WithHandlerOptions(opts...),
	)
	deviceTelemetryGetSummariesHandler := connect.NewUnaryHandler(
		DeviceTelemetryGetSummariesProcedure,
		svc.GetSummaries,
		connect.WithSchema(deviceTelemetryMethods.ByName("GetSummaries")),
		connect.WithHandlerOptions(opts...),
	)
	deviceTelemetryExportReadingsHandler := connect.NewUnaryHandler(
		DeviceTelemetryExportReadingsProcedure,
		svc.ExportReadings,
		connect.WithSchema(deviceTelemetryMethods.ByName("ExportReadings")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pkg.proto.telemetry.v2.DeviceTelemetry/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeviceTelemetryGetDeviceStatesProcedure:
			deviceTelemetryGetDeviceStatesHandler.ServeHTTP(w, r)
		case DeviceTelemetryListReadingsProcedure:
			deviceTelemetryListReadingsHandler.ServeHTTP(w, r)
		case DeviceTelemetryGetSeriesProcedure:
			deviceTelemetryGetSeriesHandler.ServeHTTP(w, r)
		case DeviceTelemetryGetSummariesProcedure:
			deviceTelemetryGetSummariesHandler.ServeHTTP(w, r)
		case DeviceTelemetryExportReadingsProcedure:
			deviceTelemetryExportReadingsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeviceTelemetryHandler returns CodeUnimplemented from all methods.
type UnimplementedDeviceTelemetryHandler struct{}

func (UnimplementedDeviceTelemetryHandler) GetDeviceStates(context.Context, *connect.Request[v2.GetDeviceStatesRequest]) (*connect.Response[v2.GetDeviceStatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.proto.telemetry.v2.DeviceTelemetry.GetDeviceStates is not implemented"))
}

func (UnimplementedDeviceTelemetryHandler) ListReadings(context.Context, *connect.Request[v2.ListReadingsRequest]) (*connect.Response[v2.ListReadingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.proto.telemetry.v2.DeviceTelemetry.ListReadings is not implemented"))
}

func (UnimplementedDeviceTelemetryHandler) GetSeries(context.Context, *connect.Request[v2.GetSeriesRequest]) (*connect.Response[v2.GetSeriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.proto.telemetry.v2.DeviceTelemetry.GetSeries is not implemented"))
}

func (UnimplementedDeviceTelemetryHandler) GetSummaries(context.Context, *connect.Request[v2.GetSummariesRequest]) (*connect.Response[v2.GetSummariesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.proto.telemetry.v2.DeviceTelemetry.GetSummaries is not implemented"))
}

func (UnimplementedDeviceTelemetryHandler) ExportReadings(context.Context, *connect.Request[v2.ExportReadingsRequest]) (*connect.Response[v2.ExportReadingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.proto.telemetry.v2.DeviceTelemetry.ExportReadings is not implemented"))
}
