// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.3
// source: pkg/proto/gateway/v2/analytics.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // RFC3339 or relative like "now-6h"
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // RFC3339 or "now"
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`                    // e.g. "UTC", "America/Los_Angeles"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TimeRange) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TimeRange) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                // optional
	DeviceTypeId  string                 `protobuf:"bytes,2,opt,name=device_type_id,json=deviceTypeId,proto3" json:"device_type_id,omitempty"`  // optional
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                      // optional
	ApplicationId string                 `protobuf:"bytes,4,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"` // optional
	HardwareIds   []string               `protobuf:"bytes,5,rep,name=hardware_ids,json=hardwareIds,proto3" json:"hardware_ids,omitempty"`       // optional (gateway hardware_id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Filter) GetDeviceTypeId() string {
	if x != nil {
		return x.DeviceTypeId
	}
	return ""
}

func (x *Filter) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Filter) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Filter) GetHardwareIds() []string {
	if x != nil {
		return x.HardwareIds
	}
	return nil
}

type BucketSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FixedInterval string                 `protobuf:"bytes,1,opt,name=fixed_interval,json=fixedInterval,proto3" json:"fixed_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketSpec) Reset() {
	*x = BucketSpec{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSpec) ProtoMessage() {}

func (x *BucketSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSpec.ProtoReflect.Descriptor instead.
func (*BucketSpec) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *BucketSpec) GetFixedInterval() string {
	if x != nil {
		return x.FixedInterval
	}
	return ""
}

type SeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            string                 `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesPoint) Reset() {
	*x = SeriesPoint{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesPoint) ProtoMessage() {}

func (x *SeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesPoint.ProtoReflect.Descriptor instead.
func (*SeriesPoint) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *SeriesPoint) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *SeriesPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type BucketSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Points        []*SeriesPoint         `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketSeries) Reset() {
	*x = BucketSeries{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSeries) ProtoMessage() {}

func (x *BucketSeries) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSeries.ProtoReflect.Descriptor instead.
func (*BucketSeries) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *BucketSeries) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BucketSeries) GetPoints() []*SeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetPingHistogramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Range         *TimeRange             `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	Bucket        *BucketSpec            `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	MaxBuckets    int32                  `protobuf:"varint,4,opt,name=max_buckets,json=maxBuckets,proto3" json:"max_buckets,omitempty"` // default 1440
	TopN          int32                  `protobuf:"varint,5,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`                   // split by top gateways
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPingHistogramRequest) Reset() {
	*x = GetPingHistogramRequest{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPingHistogramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPingHistogramRequest) ProtoMessage() {}

func (x *GetPingHistogramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPingHistogramRequest.ProtoReflect.Descriptor instead.
func (*GetPingHistogramRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetPingHistogramRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetPingHistogramRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *GetPingHistogramRequest) GetBucket() *BucketSpec {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *GetPingHistogramRequest) GetMaxBuckets() int32 {
	if x != nil {
		return x.MaxBuckets
	}
	return 0
}

func (x *GetPingHistogramRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type GetPingHistogramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*BucketSeries        `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPingHistogramResponse) Reset() {
	*x = GetPingHistogramResponse{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPingHistogramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPingHistogramResponse) ProtoMessage() {}

func (x *GetPingHistogramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPingHistogramResponse.ProtoReflect.Descriptor instead.
func (*GetPingHistogramResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetPingHistogramResponse) GetSeries() []*BucketSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

type HistogramBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           float64                `protobuf:"fixed64,1,opt,name=key,proto3" json:"key,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramBucket) Reset() {
	*x = HistogramBucket{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramBucket) ProtoMessage() {}

func (x *HistogramBucket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramBucket.ProtoReflect.Descriptor instead.
func (*HistogramBucket) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *HistogramBucket) GetKey() float64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *HistogramBucket) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetGatewayStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Range         *TimeRange             `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	TopN          int32                  `protobuf:"varint,3,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayStatsRequest) Reset() {
	*x = GetGatewayStatsRequest{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayStatsRequest) ProtoMessage() {}

func (x *GetGatewayStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetGatewayStatsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetGatewayStatsRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *GetGatewayStatsRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type GatewayStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HardwareId          string                 `protobuf:"bytes,1,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	UniqueDevices       uint64                 `protobuf:"varint,2,opt,name=unique_devices,json=uniqueDevices,proto3" json:"unique_devices,omitempty"`
	RxPacketsReceived   uint64                 `protobuf:"varint,3,opt,name=rx_packets_received,json=rxPacketsReceived,proto3" json:"rx_packets_received,omitempty"`
	RxPacketsReceivedOk uint64                 `protobuf:"varint,4,opt,name=rx_packets_received_ok,json=rxPacketsReceivedOk,proto3" json:"rx_packets_received_ok,omitempty"`
	SuccessRatio        float64                `protobuf:"fixed64,5,opt,name=success_ratio,json=successRatio,proto3" json:"success_ratio,omitempty"` // ok/received
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GatewayStats) Reset() {
	*x = GatewayStats{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStats) ProtoMessage() {}

func (x *GatewayStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStats.ProtoReflect.Descriptor instead.
func (*GatewayStats) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayStats) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *GatewayStats) GetUniqueDevices() uint64 {
	if x != nil {
		return x.UniqueDevices
	}
	return 0
}

func (x *GatewayStats) GetRxPacketsReceived() uint64 {
	if x != nil {
		return x.RxPacketsReceived
	}
	return 0
}

func (x *GatewayStats) GetRxPacketsReceivedOk() uint64 {
	if x != nil {
		return x.RxPacketsReceivedOk
	}
	return 0
}

func (x *GatewayStats) GetSuccessRatio() float64 {
	if x != nil {
		return x.SuccessRatio
	}
	return 0
}

type GetGatewayStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*GatewayStats        `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayStatsResponse) Reset() {
	*x = GetGatewayStatsResponse{}
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayStatsResponse) ProtoMessage() {}

func (x *GetGatewayStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_v2_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGatewayStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetGatewayStatsResponse) GetGateways() []*GatewayStats {
	if x != nil {
		return x.Gateways
	}
	return nil
}

var File_pkg_proto_gateway_v2_analytics_proto protoreflect.FileDescriptor

const file_pkg_proto_gateway_v2_analytics_proto_rawDesc = "" +
	"\n" +
	"$pkg/proto/gateway/v2/analytics.proto\x12\x14pkg.proto.gateway.v2\"a\n" +
	"\tTimeRange\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"\xae\x01\n" +
	"\x06Filter\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12$\n" +
	"\x0edevice_type_id\x18\x02 \x01(\tR\fdeviceTypeId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x0eapplication_id\x18\x04 \x01(\tR\rapplicationId\x12!\n" +
	"\fhardware_ids\x18\x05 \x03(\tR\vhardwareIds\"3\n" +
	"\n" +
	"BucketSpec\x12%\n" +
	"\x0efixed_interval\x18\x01 \x01(\tR\rfixedInterval\"3\n" +
	"\vSeriesPoint\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\tR\x02ts\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"[\n" +
	"\fBucketSeries\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x06points\x18\x02 \x03(\v2!.pkg.proto.gateway.v2.SeriesPointR\x06points\"\xf6\x01\n" +
	"\x17GetPingHistogramRequest\x124\n" +
	"\x06filter\x18\x01 \x01(\v2\x1c.pkg.proto.gateway.v2.FilterR\x06filter\x125\n" +
	"\x05range\x18\x02 \x01(\v2\x1f.pkg.proto.gateway.v2.TimeRangeR\x05range\x128\n" +
	"\x06bucket\x18\x03 \x01(\v2 .pkg.proto.gateway.v2.BucketSpecR\x06bucket\x12\x1f\n" +
	"\vmax_buckets\x18\x04 \x01(\x05R\n" +
	"maxBuckets\x12\x13\n" +
	"\x05top_n\x18\x05 \x01(\x05R\x04topN\"V\n" +
	"\x18GetPingHistogramResponse\x12:\n" +
	"\x06series\x18\x01 \x03(\v2\".pkg.proto.gateway.v2.BucketSeriesR\x06series\"9\n" +
	"\x0fHistogramBucket\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x01R\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\x9a\x01\n" +
	"\x16GetGatewayStatsRequest\x124\n" +
	"\x06filter\x18\x01 \x01(\v2\x1c.pkg.proto.gateway.v2.FilterR\x06filter\x125\n" +
	"\x05range\x18\x02 \x01(\v2\x1f.pkg.proto.gateway.v2.TimeRangeR\x05range\x12\x13\n" +
	"\x05top_n\x18\x03 \x01(\x05R\x04topN\"\xe0\x01\n" +
	"\fGatewayStats\x12\x1f\n" +
	"\vhardware_id\x18\x01 \x01(\tR\n" +
	"hardwareId\x12%\n" +
	"\x0eunique_devices\x18\x02 \x01(\x04R\runiqueDevices\x12.\n" +
	"\x13rx_packets_received\x18\x03 \x01(\x04R\x11rxPacketsReceived\x123\n" +
	"\x16rx_packets_received_ok\x18\x04 \x01(\x04R\x13rxPacketsReceivedOk\x12#\n" +
	"\rsuccess_ratio\x18\x05 \x01(\x01R\fsuccessRatio\"Y\n" +
	"\x17GetGatewayStatsResponse\x12>\n" +
	"\bgateways\x18\x01 \x03(\v2\".pkg.proto.gateway.v2.GatewayStatsR\bgateways2\xf5\x01\n" +
	"\x10GatewayAnalytics\x12q\n" +
	"\x10GetPingHistogram\x12-.pkg.proto.gateway.v2.GetPingHistogramRequest\x1a..pkg.proto.gateway.v2.GetPingHistogramResponse\x12n\n" +
	"\x0fGetGatewayStats\x12,.pkg.proto.gateway.v2.GetGatewayStatsRequest\x1a-.pkg.proto.gateway.v2.GetGatewayStatsResponseB=Z;github.com/myDevicesIoT/protos/pkg/proto/gateway/v2;gatewayb\x06proto3"

var (
	file_pkg_proto_gateway_v2_analytics_proto_rawDescOnce sync.Once
	file_pkg_proto_gateway_v2_analytics_proto_rawDescData []byte
)

func file_pkg_proto_gateway_v2_analytics_proto_rawDescGZIP() []byte {
	file_pkg_proto_gateway_v2_analytics_proto_rawDescOnce.Do(func() {
		file_pkg_proto_gateway_v2_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_gateway_v2_analytics_proto_rawDesc), len(file_pkg_proto_gateway_v2_analytics_proto_rawDesc)))
	})
	return file_pkg_proto_gateway_v2_analytics_proto_rawDescData
}

var file_pkg_proto_gateway_v2_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_proto_gateway_v2_analytics_proto_goTypes = []any{
	(*TimeRange)(nil),                // 0: pkg.proto.gateway.v2.TimeRange
	(*Filter)(nil),                   // 1: pkg.proto.gateway.v2.Filter
	(*BucketSpec)(nil),               // 2: pkg.proto.gateway.v2.BucketSpec
	(*SeriesPoint)(nil),              // 3: pkg.proto.gateway.v2.SeriesPoint
	(*BucketSeries)(nil),             // 4: pkg.proto.gateway.v2.BucketSeries
	(*GetPingHistogramRequest)(nil),  // 5: pkg.proto.gateway.v2.GetPingHistogramRequest
	(*GetPingHistogramResponse)(nil), // 6: pkg.proto.gateway.v2.GetPingHistogramResponse
	(*HistogramBucket)(nil),          // 7: pkg.proto.gateway.v2.HistogramBucket
	(*GetGatewayStatsRequest)(nil),   // 8: pkg.proto.gateway.v2.GetGatewayStatsRequest
	(*GatewayStats)(nil),             // 9: pkg.proto.gateway.v2.GatewayStats
	(*GetGatewayStatsResponse)(nil),  // 10: pkg.proto.gateway.v2.GetGatewayStatsResponse
}
var file_pkg_proto_gateway_v2_analytics_proto_depIdxs = []int32{
	3,  // 0: pkg.proto.gateway.v2.BucketSeries.points:type_name -> pkg.proto.gateway.v2.SeriesPoint
	1,  // 1: pkg.proto.gateway.v2.GetPingHistogramRequest.filter:type_name -> pkg.proto.gateway.v2.Filter
	0,  // 2: pkg.proto.gateway.v2.GetPingHistogramRequest.range:type_name -> pkg.proto.gateway.v2.TimeRange
	2,  // 3: pkg.proto.gateway.v2.GetPingHistogramRequest.bucket:type_name -> pkg.proto.gateway.v2.BucketSpec
	4,  // 4: pkg.proto.gateway.v2.GetPingHistogramResponse.series:type_name -> pkg.proto.gateway.v2.BucketSeries
	1,  // 5: pkg.proto.gateway.v2.GetGatewayStatsRequest.filter:type_name -> pkg.proto.gateway.v2.Filter
	0,  // 6: pkg.proto.gateway.v2.GetGatewayStatsRequest.range:type_name -> pkg.proto.gateway.v2.TimeRange
	9,  // 7: pkg.proto.gateway.v2.GetGatewayStatsResponse.gateways:type_name -> pkg.proto.gateway.v2.GatewayStats
	5,  // 8: pkg.proto.gateway.v2.GatewayAnalytics.GetPingHistogram:input_type -> pkg.proto.gateway.v2.GetPingHistogramRequest
	8,  // 9: pkg.proto.gateway.v2.GatewayAnalytics.GetGatewayStats:input_type -> pkg.proto.gateway.v2.GetGatewayStatsRequest
	6,  // 10: pkg.proto.gateway.v2.GatewayAnalytics.GetPingHistogram:output_type -> pkg.proto.gateway.v2.GetPingHistogramResponse
	10, // 11: pkg.proto.gateway.v2.GatewayAnalytics.GetGatewayStats:output_type -> pkg.proto.gateway.v2.GetGatewayStatsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_gateway_v2_analytics_proto_init() }
func file_pkg_proto_gateway_v2_analytics_proto_init() {
	if File_pkg_proto_gateway_v2_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_gateway_v2_analytics_proto_rawDesc), len(file_pkg_proto_gateway_v2_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_gateway_v2_analytics_proto_goTypes,
		DependencyIndexes: file_pkg_proto_gateway_v2_analytics_proto_depIdxs,
		MessageInfos:      file_pkg_proto_gateway_v2_analytics_proto_msgTypes,
	}.Build()
	File_pkg_proto_gateway_v2_analytics_proto = out.File
	file_pkg_proto_gateway_v2_analytics_proto_goTypes = nil
	file_pkg_proto_gateway_v2_analytics_proto_depIdxs = nil
}
