// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/proto/reading/v1/types.proto

package reading

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _types_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on ListReadingsParam with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ListReadingsParam) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListReadingsParamValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DeviceId

	// no validation rules for Type

	// no validation rules for StartDate

	// no validation rules for EndDate

	// no validation rules for Units

	// no validation rules for Event

	// no validation rules for ApplicationId

	return nil
}

// ListReadingsParamValidationError is the validation error returned by
// ListReadingsParam.Validate if the designated constraints aren't met.
type ListReadingsParamValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReadingsParamValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReadingsParamValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReadingsParamValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReadingsParamValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReadingsParamValidationError) ErrorName() string {
	return "ListReadingsParamValidationError"
}

// Error satisfies the builtin error interface
func (e ListReadingsParamValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReadingsParam.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReadingsParamValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReadingsParamValidationError{}

// Validate checks the field values on ListReadingsOptions with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListReadingsOptions) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetOrderFields() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListReadingsOptionsValidationError{
					field:  fmt.Sprintf("OrderFields[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListReadingsOptionsValidationError is the validation error returned by
// ListReadingsOptions.Validate if the designated constraints aren't met.
type ListReadingsOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReadingsOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReadingsOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReadingsOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReadingsOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReadingsOptionsValidationError) ErrorName() string {
	return "ListReadingsOptionsValidationError"
}

// Error satisfies the builtin error interface
func (e ListReadingsOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReadingsOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReadingsOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReadingsOptionsValidationError{}

// Validate checks the field values on Reading with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Reading) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadingValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DeviceId

	if v, ok := interface{}(m.GetSensors()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadingValidationError{
				field:  "Sensors",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CorrelationId

	// no validation rules for ApplicationId

	if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadingValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ReadingValidationError is the validation error returned by Reading.Validate
// if the designated constraints aren't met.
type ReadingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadingValidationError) ErrorName() string { return "ReadingValidationError" }

// Error satisfies the builtin error interface
func (e ReadingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReading.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadingValidationError{}

// Validate checks the field values on Readings with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Readings) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ReadingsValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadingsValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ReadingsValidationError is the validation error returned by
// Readings.Validate if the designated constraints aren't met.
type ReadingsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadingsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadingsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadingsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadingsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadingsValidationError) ErrorName() string { return "ReadingsValidationError" }

// Error satisfies the builtin error interface
func (e ReadingsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReadings.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadingsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadingsValidationError{}
