// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/proto/telemetry/v1/telemetry_analytics.proto

package telemetryconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/myDevicesIoT/protos/pkg/proto/telemetry/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelemetryAnalyticsName is the fully-qualified name of the TelemetryAnalytics service.
	TelemetryAnalyticsName = "pkg.proto.telemetry.v1.TelemetryAnalytics"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelemetryAnalyticsSearchEventsProcedure is the fully-qualified name of the TelemetryAnalytics's
	// SearchEvents RPC.
	TelemetryAnalyticsSearchEventsProcedure = "/pkg.proto.telemetry.v1.TelemetryAnalytics/SearchEvents"
	// TelemetryAnalyticsGetTimeHistogramProcedure is the fully-qualified name of the
	// TelemetryAnalytics's GetTimeHistogram RPC.
	TelemetryAnalyticsGetTimeHistogramProcedure = "/pkg.proto.telemetry.v1.TelemetryAnalytics/GetTimeHistogram"
	// TelemetryAnalyticsGetAggregationsProcedure is the fully-qualified name of the
	// TelemetryAnalytics's GetAggregations RPC.
	TelemetryAnalyticsGetAggregationsProcedure = "/pkg.proto.telemetry.v1.TelemetryAnalytics/GetAggregations"
	// TelemetryAnalyticsGetLatestEventsProcedure is the fully-qualified name of the
	// TelemetryAnalytics's GetLatestEvents RPC.
	TelemetryAnalyticsGetLatestEventsProcedure = "/pkg.proto.telemetry.v1.TelemetryAnalytics/GetLatestEvents"
)

// TelemetryAnalyticsClient is a client for the pkg.proto.telemetry.v1.TelemetryAnalytics service.
type TelemetryAnalyticsClient interface {
	SearchEvents(context.Context, *connect.Request[v1.SearchEventsRequest]) (*connect.Response[v1.SearchEventsResponse], error)
	GetTimeHistogram(context.Context, *connect.Request[v1.GetTimeHistogramRequest]) (*connect.Response[v1.GetTimeHistogramResponse], error)
	GetAggregations(context.Context, *connect.Request[v1.GetAggregationsRequest]) (*connect.Response[v1.GetAggregationsResponse], error)
	GetLatestEvents(context.Context, *connect.Request[v1.GetLatestEventsRequest]) (*connect.Response[v1.GetLatestEventsResponse], error)
}

// NewTelemetryAnalyticsClient constructs a client for the pkg.proto.telemetry.v1.TelemetryAnalytics
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelemetryAnalyticsClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelemetryAnalyticsClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telemetryAnalyticsMethods := v1.File_pkg_proto_telemetry_v1_telemetry_analytics_proto.Services().ByName("TelemetryAnalytics").Methods()
	return &telemetryAnalyticsClient{
		searchEvents: connect.NewClient[v1.SearchEventsRequest, v1.SearchEventsResponse](
			httpClient,
			baseURL+TelemetryAnalyticsSearchEventsProcedure,
			connect.WithSchema(telemetryAnalyticsMethods.ByName("SearchEvents")),
			connect.WithClientOptions(opts...),
		),
		getTimeHistogram: connect.NewClient[v1.GetTimeHistogramRequest, v1.GetTimeHistogramResponse](
			httpClient,
			baseURL+TelemetryAnalyticsGetTimeHistogramProcedure,
			connect.WithSchema(telemetryAnalyticsMethods.ByName("GetTimeHistogram")),
			connect.WithClientOptions(opts...),
		),
		getAggregations: connect.NewClient[v1.GetAggregationsRequest, v1.GetAggregationsResponse](
			httpClient,
			baseURL+TelemetryAnalyticsGetAggregationsProcedure,
			connect.WithSchema(telemetryAnalyticsMethods.ByName("GetAggregations")),
			connect.WithClientOptions(opts...),
		),
		getLatestEvents: connect.NewClient[v1.GetLatestEventsRequest, v1.GetLatestEventsResponse](
			httpClient,
			baseURL+TelemetryAnalyticsGetLatestEventsProcedure,
			connect.WithSchema(telemetryAnalyticsMethods.ByName("GetLatestEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telemetryAnalyticsClient implements TelemetryAnalyticsClient.
type telemetryAnalyticsClient struct {
	searchEvents     *connect.Client[v1.SearchEventsRequest, v1.SearchEventsResponse]
	getTimeHistogram *connect.Client[v1.GetTimeHistogramRequest, v1.GetTimeHistogramResponse]
	getAggregations  *connect.Client[v1.GetAggregationsRequest, v1.GetAggregationsResponse]
	getLatestEvents  *connect.Client[v1.GetLatestEventsRequest, v1.GetLatestEventsResponse]
}

// SearchEvents calls pkg.proto.telemetry.v1.TelemetryAnalytics.SearchEvents.
func (c *telemetryAnalyticsClient) SearchEvents(ctx context.Context, req *connect.Request[v1.SearchEventsRequest]) (*connect.Response[v1.SearchEventsResponse], error) {
	return c.searchEvents.CallUnary(ctx, req)
}

// GetTimeHistogram calls pkg.proto.telemetry.v1.TelemetryAnalytics.GetTimeHistogram.
func (c *telemetryAnalyticsClient) GetTimeHistogram(ctx context.Context, req *connect.Request[v1.GetTimeHistogramRequest]) (*connect.Response[v1.GetTimeHistogramResponse], error) {
	return c.getTimeHistogram.CallUnary(ctx, req)
}

// GetAggregations calls pkg.proto.telemetry.v1.TelemetryAnalytics.GetAggregations.
func (c *telemetryAnalyticsClient) GetAggregations(ctx context.Context, req *connect.Request[v1.GetAggregationsRequest]) (*connect.Response[v1.GetAggregationsResponse], error) {
	return c.getAggregations.CallUnary(ctx, req)
}

// GetLatestEvents calls pkg.proto.telemetry.v1.TelemetryAnalytics.GetLatestEvents.
func (c *telemetryAnalyticsClient) GetLatestEvents(ctx context.Context, req *connect.Request[v1.GetLatestEventsRequest]) (*connect.Response[v1.GetLatestEventsResponse], error) {
	return c.getLatestEvents.CallUnary(ctx, req)
}

// TelemetryAnalyticsHandler is an implementation of the pkg.proto.telemetry.v1.TelemetryAnalytics
// service.
type TelemetryAnalyticsHandler interface {
	SearchEvents(context.Context, *connect.Request[v1.SearchEventsRequest]) (*connect.Response[v1.SearchEventsResponse], error)
	GetTimeHistogram(context.Context, *connect.Request[v1.GetTimeHistogramRequest]) (*connect.Response[v1.GetTimeHistogramResponse], error)
	GetAggregations(context.Context, *connect.Request[v1.GetAggregationsRequest]) (*connect.Response[v1.GetAggregationsResponse], error)
	GetLatestEvents(context.Context, *connect.Request[v1.GetLatestEventsRequest]) (*connect.Response[v1.GetLatestEventsResponse], error)
}

// NewTelemetryAnalyticsHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelemetryAnalyticsHandler(svc TelemetryAnalyticsHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telemetryAnalyticsMethods := v1.File_pkg_proto_telemetry_v1_telemetry_analytics_proto.Services().ByName("TelemetryAnalytics").Methods()
	telemetryAnalyticsSearchEventsHandler := connect.NewUnaryHandler(
		TelemetryAnalyticsSearchEventsProcedure,
		svc.SearchEvents,
		connect.WithSchema(telemetryAnalyticsMethods.ByName("SearchEvents")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryAnalyticsGetTimeHistogramHandler := connect.NewUnaryHandler(
		TelemetryAnalyticsGetTimeHistogramProcedure,
		svc.GetTimeHistogram,
		connect.WithSchema(telemetryAnalyticsMethods.ByName("GetTimeHistogram")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryAnalyticsGetAggregationsHandler := connect.NewUnaryHandler(
		TelemetryAnalyticsGetAggregationsProcedure,
		svc.GetAggregations,
		connect.WithSchema(telemetryAnalyticsMethods.ByName("GetAggregations")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryAnalyticsGetLatestEventsHandler := connect.NewUnaryHandler(
		TelemetryAnalyticsGetLatestEventsProcedure,
		svc.GetLatestEvents,
		connect.WithSchema(telemetryAnalyticsMethods.ByName("GetLatestEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pkg.proto.telemetry.v1.TelemetryAnalytics/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelemetryAnalyticsSearchEventsProcedure:
			telemetryAnalyticsSearchEventsHandler.ServeHTTP(w, r)
		case TelemetryAnalyticsGetTimeHistogramProcedure:
			telemetryAnalyticsGetTimeHistogramHandler.ServeHTTP(w, r)
		case TelemetryAnalyticsGetAggregationsProcedure:
			telemetryAnalyticsGetAggregationsHandler.ServeHTTP(w, r)
		case TelemetryAnalyticsGetLatestEventsProcedure:
			telemetryAnalyticsGetLatestEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelemetryAnalyticsHandler returns CodeUnimplemented from all methods.
type UnimplementedTelemetryAnalyticsHandler struct{}

func (UnimplementedTelemetryAnalyticsHandler) SearchEvents(context.Context, *connect.Request[v1.SearchEventsRequest]) (*connect.Response[v1.SearchEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.proto.telemetry.v1.TelemetryAnalytics.SearchEvents is not implemented"))
}

func (UnimplementedTelemetryAnalyticsHandler) GetTimeHistogram(context.Context, *connect.Request[v1.GetTimeHistogramRequest]) (*connect.Response[v1.GetTimeHistogramResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.proto.telemetry.v1.TelemetryAnalytics.GetTimeHistogram is not implemented"))
}

func (UnimplementedTelemetryAnalyticsHandler) GetAggregations(context.Context, *connect.Request[v1.GetAggregationsRequest]) (*connect.Response[v1.GetAggregationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.proto.telemetry.v1.TelemetryAnalytics.GetAggregations is not implemented"))
}

func (UnimplementedTelemetryAnalyticsHandler) GetLatestEvents(context.Context, *connect.Request[v1.GetLatestEventsRequest]) (*connect.Response[v1.GetLatestEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.proto.telemetry.v1.TelemetryAnalytics.GetLatestEvents is not implemented"))
}
