// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: pkg/proto/telemetry/v2/device_telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceTelemetry_GetDeviceStates_FullMethodName = "/pkg.proto.telemetry.v2.DeviceTelemetry/GetDeviceStates"
	DeviceTelemetry_ListReadings_FullMethodName    = "/pkg.proto.telemetry.v2.DeviceTelemetry/ListReadings"
	DeviceTelemetry_GetSeries_FullMethodName       = "/pkg.proto.telemetry.v2.DeviceTelemetry/GetSeries"
	DeviceTelemetry_GetSummaries_FullMethodName    = "/pkg.proto.telemetry.v2.DeviceTelemetry/GetSummaries"
	DeviceTelemetry_ExportReadings_FullMethodName  = "/pkg.proto.telemetry.v2.DeviceTelemetry/ExportReadings"
)

// DeviceTelemetryClient is the client API for DeviceTelemetry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeviceTelemetry serves device state, history logs, charts and exports
// for dashboards. Replaces the delorean-es read API.
type DeviceTelemetryClient interface {
	GetDeviceStates(ctx context.Context, in *GetDeviceStatesRequest, opts ...grpc.CallOption) (*GetDeviceStatesResponse, error)
	ListReadings(ctx context.Context, in *ListReadingsRequest, opts ...grpc.CallOption) (*ListReadingsResponse, error)
	GetSeries(ctx context.Context, in *GetSeriesRequest, opts ...grpc.CallOption) (*GetSeriesResponse, error)
	GetSummaries(ctx context.Context, in *GetSummariesRequest, opts ...grpc.CallOption) (*GetSummariesResponse, error)
	ExportReadings(ctx context.Context, in *ExportReadingsRequest, opts ...grpc.CallOption) (*ExportReadingsResponse, error)
}

type deviceTelemetryClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceTelemetryClient(cc grpc.ClientConnInterface) DeviceTelemetryClient {
	return &deviceTelemetryClient{cc}
}

func (c *deviceTelemetryClient) GetDeviceStates(ctx context.Context, in *GetDeviceStatesRequest, opts ...grpc.CallOption) (*GetDeviceStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceStatesResponse)
	err := c.cc.Invoke(ctx, DeviceTelemetry_GetDeviceStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTelemetryClient) ListReadings(ctx context.Context, in *ListReadingsRequest, opts ...grpc.CallOption) (*ListReadingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReadingsResponse)
	err := c.cc.Invoke(ctx, DeviceTelemetry_ListReadings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTelemetryClient) GetSeries(ctx context.Context, in *GetSeriesRequest, opts ...grpc.CallOption) (*GetSeriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeriesResponse)
	err := c.cc.Invoke(ctx, DeviceTelemetry_GetSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTelemetryClient) GetSummaries(ctx context.Context, in *GetSummariesRequest, opts ...grpc.CallOption) (*GetSummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSummariesResponse)
	err := c.cc.Invoke(ctx, DeviceTelemetry_GetSummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTelemetryClient) ExportReadings(ctx context.Context, in *ExportReadingsRequest, opts ...grpc.CallOption) (*ExportReadingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReadingsResponse)
	err := c.cc.Invoke(ctx, DeviceTelemetry_ExportReadings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceTelemetryServer is the server API for DeviceTelemetry service.
// All implementations should embed UnimplementedDeviceTelemetryServer
// for forward compatibility.
//
// DeviceTelemetry serves device state, history logs, charts and exports
// for dashboards. Replaces the delorean-es read API.
type DeviceTelemetryServer interface {
	GetDeviceStates(context.Context, *GetDeviceStatesRequest) (*GetDeviceStatesResponse, error)
	ListReadings(context.Context, *ListReadingsRequest) (*ListReadingsResponse, error)
	GetSeries(context.Context, *GetSeriesRequest) (*GetSeriesResponse, error)
	GetSummaries(context.Context, *GetSummariesRequest) (*GetSummariesResponse, error)
	ExportReadings(context.Context, *ExportReadingsRequest) (*ExportReadingsResponse, error)
}

// UnimplementedDeviceTelemetryServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceTelemetryServer struct{}

func (UnimplementedDeviceTelemetryServer) GetDeviceStates(context.Context, *GetDeviceStatesRequest) (*GetDeviceStatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceStates not implemented")
}
func (UnimplementedDeviceTelemetryServer) ListReadings(context.Context, *ListReadingsRequest) (*ListReadingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReadings not implemented")
}
func (UnimplementedDeviceTelemetryServer) GetSeries(context.Context, *GetSeriesRequest) (*GetSeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeries not implemented")
}
func (UnimplementedDeviceTelemetryServer) GetSummaries(context.Context, *GetSummariesRequest) (*GetSummariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummaries not implemented")
}
func (UnimplementedDeviceTelemetryServer) ExportReadings(context.Context, *ExportReadingsRequest) (*ExportReadingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportReadings not implemented")
}
func (UnimplementedDeviceTelemetryServer) testEmbeddedByValue() {}

// UnsafeDeviceTelemetryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceTelemetryServer will
// result in compilation errors.
type UnsafeDeviceTelemetryServer interface {
	mustEmbedUnimplementedDeviceTelemetryServer()
}

func RegisterDeviceTelemetryServer(s grpc.ServiceRegistrar, srv DeviceTelemetryServer) {
	// If the following call pancis, it indicates UnimplementedDeviceTelemetryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceTelemetry_ServiceDesc, srv)
}

func _DeviceTelemetry_GetDeviceStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTelemetryServer).GetDeviceStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceTelemetry_GetDeviceStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTelemetryServer).GetDeviceStates(ctx, req.(*GetDeviceStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTelemetry_ListReadings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReadingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTelemetryServer).ListReadings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceTelemetry_ListReadings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTelemetryServer).ListReadings(ctx, req.(*ListReadingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTelemetry_GetSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTelemetryServer).GetSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceTelemetry_GetSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTelemetryServer).GetSeries(ctx, req.(*GetSeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTelemetry_GetSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTelemetryServer).GetSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceTelemetry_GetSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTelemetryServer).GetSummaries(ctx, req.(*GetSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTelemetry_ExportReadings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReadingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTelemetryServer).ExportReadings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceTelemetry_ExportReadings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTelemetryServer).ExportReadings(ctx, req.(*ExportReadingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceTelemetry_ServiceDesc is the grpc.ServiceDesc for DeviceTelemetry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceTelemetry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.proto.telemetry.v2.DeviceTelemetry",
	HandlerType: (*DeviceTelemetryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceStates",
			Handler:    _DeviceTelemetry_GetDeviceStates_Handler,
		},
		{
			MethodName: "ListReadings",
			Handler:    _DeviceTelemetry_ListReadings_Handler,
		},
		{
			MethodName: "GetSeries",
			Handler:    _DeviceTelemetry_GetSeries_Handler,
		},
		{
			MethodName: "GetSummaries",
			Handler:    _DeviceTelemetry_GetSummaries_Handler,
		},
		{
			MethodName: "ExportReadings",
			Handler:    _DeviceTelemetry_ExportReadings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/telemetry/v2/device_telemetry.proto",
}
