// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.3
// source: pkg/proto/telemetry/v2/device_telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interval int32

const (
	Interval_INTERVAL_UNSPECIFIED Interval = 0
	Interval_M1                   Interval = 1
	Interval_M5                   Interval = 2
	Interval_M15                  Interval = 3
	Interval_H1                   Interval = 4
	Interval_D1                   Interval = 5
	Interval_W1                   Interval = 6
	Interval_MO1                  Interval = 7
)

// Enum value maps for Interval.
var (
	Interval_name = map[int32]string{
		0: "INTERVAL_UNSPECIFIED",
		1: "M1",
		2: "M5",
		3: "M15",
		4: "H1",
		5: "D1",
		6: "W1",
		7: "MO1",
	}
	Interval_value = map[string]int32{
		"INTERVAL_UNSPECIFIED": 0,
		"M1":                   1,
		"M5":                   2,
		"M15":                  3,
		"H1":                   4,
		"D1":                   5,
		"W1":                   6,
		"MO1":                  7,
	}
)

func (x Interval) Enum() *Interval {
	p := new(Interval)
	*p = x
	return p
}

func (x Interval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interval) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_enumTypes[0].Descriptor()
}

func (Interval) Type() protoreflect.EnumType {
	return &file_pkg_proto_telemetry_v2_device_telemetry_proto_enumTypes[0]
}

func (x Interval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Interval.Descriptor instead.
func (Interval) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{0}
}

type Metric int32

const (
	Metric_METRIC_UNSPECIFIED Metric = 0
	Metric_MIN                Metric = 1
	Metric_MAX                Metric = 2
	Metric_AVG                Metric = 3
	Metric_SUM                Metric = 4
	Metric_COUNT              Metric = 5
	Metric_LAST               Metric = 6
)

// Enum value maps for Metric.
var (
	Metric_name = map[int32]string{
		0: "METRIC_UNSPECIFIED",
		1: "MIN",
		2: "MAX",
		3: "AVG",
		4: "SUM",
		5: "COUNT",
		6: "LAST",
	}
	Metric_value = map[string]int32{
		"METRIC_UNSPECIFIED": 0,
		"MIN":                1,
		"MAX":                2,
		"AVG":                3,
		"SUM":                4,
		"COUNT":              5,
		"LAST":               6,
	}
)

func (x Metric) Enum() *Metric {
	p := new(Metric)
	*p = x
	return p
}

func (x Metric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_enumTypes[1].Descriptor()
}

func (Metric) Type() protoreflect.EnumType {
	return &file_pkg_proto_telemetry_v2_device_telemetry_proto_enumTypes[1]
}

func (x Metric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric.Descriptor instead.
func (Metric) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{1}
}

// TimeRange bounds a query. start and end accept RFC3339, 2006-01-02,
// 2006-01-02T15:04:05, "now" and relative forms such as "now-7d".
// timezone is an IANA name used only for bucket alignment; default UTC.
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TimeRange) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *TimeRange) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// Scope narrows a request to one tenant. Both fields are optional term
// filters; an empty field means no filter.
type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Scope) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Scope) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type Geo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geo) Reset() {
	*x = Geo{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geo) ProtoMessage() {}

func (x *Geo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geo.ProtoReflect.Descriptor instead.
func (*Geo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *Geo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Geo) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

// Reading is one sensor value inside an uplink.
type Reading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Value         *float64               `protobuf:"fixed64,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	ValueText     string                 `protobuf:"bytes,4,opt,name=value_text,json=valueText,proto3" json:"value_text,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Geo           *Geo                   `protobuf:"bytes,8,opt,name=geo,proto3,oneof" json:"geo,omitempty"`
	Event         string                 `protobuf:"bytes,9,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reading) Reset() {
	*x = Reading{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reading) ProtoMessage() {}

func (x *Reading) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reading.ProtoReflect.Descriptor instead.
func (*Reading) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *Reading) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Reading) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Reading) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *Reading) GetValueText() string {
	if x != nil {
		return x.ValueText
	}
	return ""
}

func (x *Reading) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Reading) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Reading) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Reading) GetGeo() *Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *Reading) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

// Row is one uplink: every reading that arrived together.
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Readings      []*Reading             `protobuf:"bytes,3,rep,name=readings,proto3" json:"readings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Row) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Row) GetReadings() []*Reading {
	if x != nil {
		return x.Readings
	}
	return nil
}

type GetDeviceStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceIds     []string               `protobuf:"bytes,1,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"` // 1..100
	Channels      []string               `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`                    // optional filter
	Scope         *Scope                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatesRequest) Reset() {
	*x = GetDeviceStatesRequest{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatesRequest) ProtoMessage() {}

func (x *GetDeviceStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatesRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceStatesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeviceStatesRequest) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

func (x *GetDeviceStatesRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *GetDeviceStatesRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ChannelState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	SensorId      string                 `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Value         *float64               `protobuf:"fixed64,4,opt,name=value,proto3,oneof" json:"value,omitempty"`
	ValueText     string                 `protobuf:"bytes,5,opt,name=value_text,json=valueText,proto3" json:"value_text,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Geo           *Geo                   `protobuf:"bytes,9,opt,name=geo,proto3,oneof" json:"geo,omitempty"`
	Event         string                 `protobuf:"bytes,10,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelState) Reset() {
	*x = ChannelState{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelState) ProtoMessage() {}

func (x *ChannelState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelState.ProtoReflect.Descriptor instead.
func (*ChannelState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelState) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ChannelState) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *ChannelState) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *ChannelState) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *ChannelState) GetValueText() string {
	if x != nil {
		return x.ValueText
	}
	return ""
}

func (x *ChannelState) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ChannelState) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChannelState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelState) GetGeo() *Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *ChannelState) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type DeviceState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Channels      []*ChannelState        `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceState) Reset() {
	*x = DeviceState{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceState) ProtoMessage() {}

func (x *DeviceState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceState.ProtoReflect.Descriptor instead.
func (*DeviceState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceState) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceState) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *DeviceState) GetChannels() []*ChannelState {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *DeviceState) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetDeviceStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceState         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatesResponse) Reset() {
	*x = GetDeviceStatesResponse{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatesResponse) ProtoMessage() {}

func (x *GetDeviceStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatesResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceStatesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceStatesResponse) GetDevices() []*DeviceState {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ListReadingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SensorIds     []string               `protobuf:"bytes,2,rep,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	Channels      []string               `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	Range         *TimeRange             `protobuf:"bytes,4,opt,name=range,proto3" json:"range,omitempty"`
	Ascending     bool                   `protobuf:"varint,5,opt,name=ascending,proto3" json:"ascending,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // rows, default 50, max 500
	PageToken     string                 `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadingsRequest) Reset() {
	*x = ListReadingsRequest{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadingsRequest) ProtoMessage() {}

func (x *ListReadingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadingsRequest.ProtoReflect.Descriptor instead.
func (*ListReadingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *ListReadingsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ListReadingsRequest) GetSensorIds() []string {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

func (x *ListReadingsRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ListReadingsRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *ListReadingsRequest) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

func (x *ListReadingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListReadingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListReadingsRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ListReadingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadingsResponse) Reset() {
	*x = ListReadingsResponse{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadingsResponse) ProtoMessage() {}

func (x *ListReadingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadingsResponse.ProtoReflect.Descriptor instead.
func (*ListReadingsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{10}
}

func (x *ListReadingsResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListReadingsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceIds     []string               `protobuf:"bytes,1,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"` // 1..20
	SensorIds     []string               `protobuf:"bytes,2,rep,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	Range         *TimeRange             `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	Interval      Interval               `protobuf:"varint,4,opt,name=interval,proto3,enum=pkg.proto.telemetry.v2.Interval" json:"interval,omitempty"`
	MaxPoints     int32                  `protobuf:"varint,5,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	Metrics       []Metric               `protobuf:"varint,6,rep,packed,name=metrics,proto3,enum=pkg.proto.telemetry.v2.Metric" json:"metrics,omitempty"` // default MIN, MAX, AVG
	Scope         *Scope                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesRequest) Reset() {
	*x = GetSeriesRequest{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesRequest) ProtoMessage() {}

func (x *GetSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetSeriesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{11}
}

func (x *GetSeriesRequest) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

func (x *GetSeriesRequest) GetSensorIds() []string {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

func (x *GetSeriesRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *GetSeriesRequest) GetInterval() Interval {
	if x != nil {
		return x.Interval
	}
	return Interval_INTERVAL_UNSPECIFIED
}

func (x *GetSeriesRequest) GetMaxPoints() int32 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

func (x *GetSeriesRequest) GetMetrics() []Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetSeriesRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Min           *float64               `protobuf:"fixed64,2,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *float64               `protobuf:"fixed64,3,opt,name=max,proto3,oneof" json:"max,omitempty"`
	Avg           *float64               `protobuf:"fixed64,4,opt,name=avg,proto3,oneof" json:"avg,omitempty"`
	Sum           *float64               `protobuf:"fixed64,5,opt,name=sum,proto3,oneof" json:"sum,omitempty"`
	Count         int64                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Last          *float64               `protobuf:"fixed64,7,opt,name=last,proto3,oneof" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{12}
}

func (x *Point) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Point) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *Point) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *Point) GetAvg() float64 {
	if x != nil && x.Avg != nil {
		return *x.Avg
	}
	return 0
}

func (x *Point) GetSum() float64 {
	if x != nil && x.Sum != nil {
		return *x.Sum
	}
	return 0
}

func (x *Point) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Point) GetLast() float64 {
	if x != nil && x.Last != nil {
		return *x.Last
	}
	return 0
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SensorId      string                 `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Interval      Interval               `protobuf:"varint,6,opt,name=interval,proto3,enum=pkg.proto.telemetry.v2.Interval" json:"interval,omitempty"`
	Points        []*Point               `protobuf:"bytes,7,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{13}
}

func (x *Series) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Series) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Series) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Series) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Series) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Series) GetInterval() Interval {
	if x != nil {
		return x.Interval
	}
	return Interval_INTERVAL_UNSPECIFIED
}

func (x *Series) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*Series              `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesResponse) Reset() {
	*x = GetSeriesResponse{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesResponse) ProtoMessage() {}

func (x *GetSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesResponse.ProtoReflect.Descriptor instead.
func (*GetSeriesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{14}
}

func (x *GetSeriesResponse) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type GetSummariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SensorIds     []string               `protobuf:"bytes,2,rep,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	Range         *TimeRange             `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummariesRequest) Reset() {
	*x = GetSummariesRequest{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummariesRequest) ProtoMessage() {}

func (x *GetSummariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummariesRequest.ProtoReflect.Descriptor instead.
func (*GetSummariesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{15}
}

func (x *GetSummariesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetSummariesRequest) GetSensorIds() []string {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

func (x *GetSummariesRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *GetSummariesRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Min           *float64               `protobuf:"fixed64,5,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *float64               `protobuf:"fixed64,6,opt,name=max,proto3,oneof" json:"max,omitempty"`
	Avg           *float64               `protobuf:"fixed64,7,opt,name=avg,proto3,oneof" json:"avg,omitempty"`
	Sum           *float64               `protobuf:"fixed64,8,opt,name=sum,proto3,oneof" json:"sum,omitempty"`
	Count         int64                  `protobuf:"varint,9,opt,name=count,proto3" json:"count,omitempty"`
	FirstTs       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=first_ts,json=firstTs,proto3" json:"first_ts,omitempty"`
	FirstValue    *float64               `protobuf:"fixed64,11,opt,name=first_value,json=firstValue,proto3,oneof" json:"first_value,omitempty"`
	LastTs        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_ts,json=lastTs,proto3" json:"last_ts,omitempty"`
	LastValue     *float64               `protobuf:"fixed64,13,opt,name=last_value,json=lastValue,proto3,oneof" json:"last_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{16}
}

func (x *Summary) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Summary) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Summary) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Summary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Summary) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *Summary) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *Summary) GetAvg() float64 {
	if x != nil && x.Avg != nil {
		return *x.Avg
	}
	return 0
}

func (x *Summary) GetSum() float64 {
	if x != nil && x.Sum != nil {
		return *x.Sum
	}
	return 0
}

func (x *Summary) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Summary) GetFirstTs() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstTs
	}
	return nil
}

func (x *Summary) GetFirstValue() float64 {
	if x != nil && x.FirstValue != nil {
		return *x.FirstValue
	}
	return 0
}

func (x *Summary) GetLastTs() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTs
	}
	return nil
}

func (x *Summary) GetLastValue() float64 {
	if x != nil && x.LastValue != nil {
		return *x.LastValue
	}
	return 0
}

type GetSummariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*Summary             `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummariesResponse) Reset() {
	*x = GetSummariesResponse{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummariesResponse) ProtoMessage() {}

func (x *GetSummariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummariesResponse.ProtoReflect.Descriptor instead.
func (*GetSummariesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{17}
}

func (x *GetSummariesResponse) GetSummaries() []*Summary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type ExportReadingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SensorIds     []string               `protobuf:"bytes,2,rep,name=sensor_ids,json=sensorIds,proto3" json:"sensor_ids,omitempty"`
	Channels      []string               `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	Range         *TimeRange             `protobuf:"bytes,4,opt,name=range,proto3" json:"range,omitempty"`
	Ascending     bool                   `protobuf:"varint,5,opt,name=ascending,proto3" json:"ascending,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // rows, default 1000, max 10000
	Cursor        string                 `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`                      // empty on the first call
	Scope         *Scope                 `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReadingsRequest) Reset() {
	*x = ExportReadingsRequest{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReadingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReadingsRequest) ProtoMessage() {}

func (x *ExportReadingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReadingsRequest.ProtoReflect.Descriptor instead.
func (*ExportReadingsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{18}
}

func (x *ExportReadingsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ExportReadingsRequest) GetSensorIds() []string {
	if x != nil {
		return x.SensorIds
	}
	return nil
}

func (x *ExportReadingsRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ExportReadingsRequest) GetRange() *TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *ExportReadingsRequest) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

func (x *ExportReadingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ExportReadingsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ExportReadingsRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ExportReadingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReadingsResponse) Reset() {
	*x = ExportReadingsResponse{}
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReadingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReadingsResponse) ProtoMessage() {}

func (x *ExportReadingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReadingsResponse.ProtoReflect.Descriptor instead.
func (*ExportReadingsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP(), []int{19}
}

func (x *ExportReadingsResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ExportReadingsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ExportReadingsResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_pkg_proto_telemetry_v2_device_telemetry_proto protoreflect.FileDescriptor

const file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDesc = "" +
	"\n" +
	"-pkg/proto/telemetry/v2/device_telemetry.proto\x12\x16pkg.proto.telemetry.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\tTimeRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"G\n" +
	"\x05Scope\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\")\n" +
	"\x03Geo\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"\x92\x02\n" +
	"\aReading\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x19\n" +
	"\x05value\x18\x03 \x01(\x01H\x00R\x05value\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"value_text\x18\x04 \x01(\tR\tvalueText\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x122\n" +
	"\x03geo\x18\b \x01(\v2\x1b.pkg.proto.telemetry.v2.GeoH\x01R\x03geo\x88\x01\x01\x12\x14\n" +
	"\x05event\x18\t \x01(\tR\x05eventB\b\n" +
	"\x06_valueB\x06\n" +
	"\x04_geo\"\x95\x01\n" +
	"\x03Row\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12;\n" +
	"\breadings\x18\x03 \x03(\v2\x1f.pkg.proto.telemetry.v2.ReadingR\breadings\"\x88\x01\n" +
	"\x16GetDeviceStatesRequest\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x01 \x03(\tR\tdeviceIds\x12\x1a\n" +
	"\bchannels\x18\x02 \x03(\tR\bchannels\x123\n" +
	"\x05scope\x18\x03 \x01(\v2\x1d.pkg.proto.telemetry.v2.ScopeR\x05scope\"\xc3\x02\n" +
	"\fChannelState\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\tR\bsensorId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x19\n" +
	"\x05value\x18\x04 \x01(\x01H\x00R\x05value\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"value_text\x18\x05 \x01(\tR\tvalueText\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x122\n" +
	"\x03geo\x18\t \x01(\v2\x1b.pkg.proto.telemetry.v2.GeoH\x01R\x03geo\x88\x01\x01\x12\x14\n" +
	"\x05event\x18\n" +
	" \x01(\tR\x05eventB\b\n" +
	"\x06_valueB\x06\n" +
	"\x04_geo\"\xbb\x01\n" +
	"\vDeviceState\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x127\n" +
	"\tlast_seen\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12@\n" +
	"\bchannels\x18\x03 \x03(\v2$.pkg.proto.telemetry.v2.ChannelStateR\bchannels\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\"X\n" +
	"\x17GetDeviceStatesResponse\x12=\n" +
	"\adevices\x18\x01 \x03(\v2#.pkg.proto.telemetry.v2.DeviceStateR\adevices\"\xb5\x02\n" +
	"\x13ListReadingsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x02 \x03(\tR\tsensorIds\x12\x1a\n" +
	"\bchannels\x18\x03 \x03(\tR\bchannels\x127\n" +
	"\x05range\x18\x04 \x01(\v2!.pkg.proto.telemetry.v2.TimeRangeR\x05range\x12\x1c\n" +
	"\tascending\x18\x05 \x01(\bR\tascending\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\x123\n" +
	"\x05scope\x18\b \x01(\v2\x1d.pkg.proto.telemetry.v2.ScopeR\x05scope\"o\n" +
	"\x14ListReadingsResponse\x12/\n" +
	"\x04rows\x18\x01 \x03(\v2\x1b.pkg.proto.telemetry.v2.RowR\x04rows\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd5\x02\n" +
	"\x10GetSeriesRequest\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x01 \x03(\tR\tdeviceIds\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x02 \x03(\tR\tsensorIds\x127\n" +
	"\x05range\x18\x03 \x01(\v2!.pkg.proto.telemetry.v2.TimeRangeR\x05range\x12<\n" +
	"\binterval\x18\x04 \x01(\x0e2 .pkg.proto.telemetry.v2.IntervalR\binterval\x12\x1d\n" +
	"\n" +
	"max_points\x18\x05 \x01(\x05R\tmaxPoints\x128\n" +
	"\ametrics\x18\x06 \x03(\x0e2\x1e.pkg.proto.telemetry.v2.MetricR\ametrics\x123\n" +
	"\x05scope\x18\a \x01(\v2\x1d.pkg.proto.telemetry.v2.ScopeR\x05scope\"\xe7\x01\n" +
	"\x05Point\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x15\n" +
	"\x03min\x18\x02 \x01(\x01H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x03 \x01(\x01H\x01R\x03max\x88\x01\x01\x12\x15\n" +
	"\x03avg\x18\x04 \x01(\x01H\x02R\x03avg\x88\x01\x01\x12\x15\n" +
	"\x03sum\x18\x05 \x01(\x01H\x03R\x03sum\x88\x01\x01\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x03R\x05count\x12\x17\n" +
	"\x04last\x18\a \x01(\x01H\x04R\x04last\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_maxB\x06\n" +
	"\x04_avgB\x06\n" +
	"\x04_sumB\a\n" +
	"\x05_last\"\xf9\x01\n" +
	"\x06Series\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\tR\bsensorId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12<\n" +
	"\binterval\x18\x06 \x01(\x0e2 .pkg.proto.telemetry.v2.IntervalR\binterval\x125\n" +
	"\x06points\x18\a \x03(\v2\x1d.pkg.proto.telemetry.v2.PointR\x06points\"K\n" +
	"\x11GetSeriesResponse\x126\n" +
	"\x06series\x18\x01 \x03(\v2\x1e.pkg.proto.telemetry.v2.SeriesR\x06series\"\xbf\x01\n" +
	"\x13GetSummariesRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x02 \x03(\tR\tsensorIds\x127\n" +
	"\x05range\x18\x03 \x01(\v2!.pkg.proto.telemetry.v2.TimeRangeR\x05range\x123\n" +
	"\x05scope\x18\x04 \x01(\v2\x1d.pkg.proto.telemetry.v2.ScopeR\x05scope\"\xcf\x03\n" +
	"\aSummary\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x15\n" +
	"\x03min\x18\x05 \x01(\x01H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x06 \x01(\x01H\x01R\x03max\x88\x01\x01\x12\x15\n" +
	"\x03avg\x18\a \x01(\x01H\x02R\x03avg\x88\x01\x01\x12\x15\n" +
	"\x03sum\x18\b \x01(\x01H\x03R\x03sum\x88\x01\x01\x12\x14\n" +
	"\x05count\x18\t \x01(\x03R\x05count\x125\n" +
	"\bfirst_ts\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\afirstTs\x12$\n" +
	"\vfirst_value\x18\v \x01(\x01H\x04R\n" +
	"firstValue\x88\x01\x01\x123\n" +
	"\alast_ts\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x06lastTs\x12\"\n" +
	"\n" +
	"last_value\x18\r \x01(\x01H\x05R\tlastValue\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_maxB\x06\n" +
	"\x04_avgB\x06\n" +
	"\x04_sumB\x0e\n" +
	"\f_first_valueB\r\n" +
	"\v_last_value\"U\n" +
	"\x14GetSummariesResponse\x12=\n" +
	"\tsummaries\x18\x01 \x03(\v2\x1f.pkg.proto.telemetry.v2.SummaryR\tsummaries\"\xb0\x02\n" +
	"\x15ExportReadingsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"sensor_ids\x18\x02 \x03(\tR\tsensorIds\x12\x1a\n" +
	"\bchannels\x18\x03 \x03(\tR\bchannels\x127\n" +
	"\x05range\x18\x04 \x01(\v2!.pkg.proto.telemetry.v2.TimeRangeR\x05range\x12\x1c\n" +
	"\tascending\x18\x05 \x01(\bR\tascending\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\a \x01(\tR\x06cursor\x123\n" +
	"\x05scope\x18\b \x01(\v2\x1d.pkg.proto.telemetry.v2.ScopeR\x05scope\"u\n" +
	"\x16ExportReadingsResponse\x12/\n" +
	"\x04rows\x18\x01 \x03(\v2\x1b.pkg.proto.telemetry.v2.RowR\x04rows\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done*^\n" +
	"\bInterval\x12\x18\n" +
	"\x14INTERVAL_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02M1\x10\x01\x12\x06\n" +
	"\x02M5\x10\x02\x12\a\n" +
	"\x03M15\x10\x03\x12\x06\n" +
	"\x02H1\x10\x04\x12\x06\n" +
	"\x02D1\x10\x05\x12\x06\n" +
	"\x02W1\x10\x06\x12\a\n" +
	"\x03MO1\x10\a*Y\n" +
	"\x06Metric\x12\x16\n" +
	"\x12METRIC_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03MIN\x10\x01\x12\a\n" +
	"\x03MAX\x10\x02\x12\a\n" +
	"\x03AVG\x10\x03\x12\a\n" +
	"\x03SUM\x10\x04\x12\t\n" +
	"\x05COUNT\x10\x05\x12\b\n" +
	"\x04LAST\x10\x062\xae\x04\n" +
	"\x0fDeviceTelemetry\x12r\n" +
	"\x0fGetDeviceStates\x12..pkg.proto.telemetry.v2.GetDeviceStatesRequest\x1a/.pkg.proto.telemetry.v2.GetDeviceStatesResponse\x12i\n" +
	"\fListReadings\x12+.pkg.proto.telemetry.v2.ListReadingsRequest\x1a,.pkg.proto.telemetry.v2.ListReadingsResponse\x12`\n" +
	"\tGetSeries\x12(.pkg.proto.telemetry.v2.GetSeriesRequest\x1a).pkg.proto.telemetry.v2.GetSeriesResponse\x12i\n" +
	"\fGetSummaries\x12+.pkg.proto.telemetry.v2.GetSummariesRequest\x1a,.pkg.proto.telemetry.v2.GetSummariesResponse\x12o\n" +
	"\x0eExportReadings\x12-.pkg.proto.telemetry.v2.ExportReadingsRequest\x1a..pkg.proto.telemetry.v2.ExportReadingsResponseBAZ?github.com/myDevicesIoT/protos/pkg/proto/telemetry/v2;telemetryb\x06proto3"

var (
	file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescOnce sync.Once
	file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescData []byte
)

func file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescGZIP() []byte {
	file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescOnce.Do(func() {
		file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDesc), len(file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDesc)))
	})
	return file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDescData
}

var file_pkg_proto_telemetry_v2_device_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_proto_telemetry_v2_device_telemetry_proto_goTypes = []any{
	(Interval)(0),                   // 0: pkg.proto.telemetry.v2.Interval
	(Metric)(0),                     // 1: pkg.proto.telemetry.v2.Metric
	(*TimeRange)(nil),               // 2: pkg.proto.telemetry.v2.TimeRange
	(*Scope)(nil),                   // 3: pkg.proto.telemetry.v2.Scope
	(*Geo)(nil),                     // 4: pkg.proto.telemetry.v2.Geo
	(*Reading)(nil),                 // 5: pkg.proto.telemetry.v2.Reading
	(*Row)(nil),                     // 6: pkg.proto.telemetry.v2.Row
	(*GetDeviceStatesRequest)(nil),  // 7: pkg.proto.telemetry.v2.GetDeviceStatesRequest
	(*ChannelState)(nil),            // 8: pkg.proto.telemetry.v2.ChannelState
	(*DeviceState)(nil),             // 9: pkg.proto.telemetry.v2.DeviceState
	(*GetDeviceStatesResponse)(nil), // 10: pkg.proto.telemetry.v2.GetDeviceStatesResponse
	(*ListReadingsRequest)(nil),     // 11: pkg.proto.telemetry.v2.ListReadingsRequest
	(*ListReadingsResponse)(nil),    // 12: pkg.proto.telemetry.v2.ListReadingsResponse
	(*GetSeriesRequest)(nil),        // 13: pkg.proto.telemetry.v2.GetSeriesRequest
	(*Point)(nil),                   // 14: pkg.proto.telemetry.v2.Point
	(*Series)(nil),                  // 15: pkg.proto.telemetry.v2.Series
	(*GetSeriesResponse)(nil),       // 16: pkg.proto.telemetry.v2.GetSeriesResponse
	(*GetSummariesRequest)(nil),     // 17: pkg.proto.telemetry.v2.GetSummariesRequest
	(*Summary)(nil),                 // 18: pkg.proto.telemetry.v2.Summary
	(*GetSummariesResponse)(nil),    // 19: pkg.proto.telemetry.v2.GetSummariesResponse
	(*ExportReadingsRequest)(nil),   // 20: pkg.proto.telemetry.v2.ExportReadingsRequest
	(*ExportReadingsResponse)(nil),  // 21: pkg.proto.telemetry.v2.ExportReadingsResponse
	(*timestamppb.Timestamp)(nil),   // 22: google.protobuf.Timestamp
}
var file_pkg_proto_telemetry_v2_device_telemetry_proto_depIdxs = []int32{
	4,  // 0: pkg.proto.telemetry.v2.Reading.geo:type_name -> pkg.proto.telemetry.v2.Geo
	22, // 1: pkg.proto.telemetry.v2.Row.ts:type_name -> google.protobuf.Timestamp
	5,  // 2: pkg.proto.telemetry.v2.Row.readings:type_name -> pkg.proto.telemetry.v2.Reading
	3,  // 3: pkg.proto.telemetry.v2.GetDeviceStatesRequest.scope:type_name -> pkg.proto.telemetry.v2.Scope
	22, // 4: pkg.proto.telemetry.v2.ChannelState.ts:type_name -> google.protobuf.Timestamp
	4,  // 5: pkg.proto.telemetry.v2.ChannelState.geo:type_name -> pkg.proto.telemetry.v2.Geo
	22, // 6: pkg.proto.telemetry.v2.DeviceState.last_seen:type_name -> google.protobuf.Timestamp
	8,  // 7: pkg.proto.telemetry.v2.DeviceState.channels:type_name -> pkg.proto.telemetry.v2.ChannelState
	9,  // 8: pkg.proto.telemetry.v2.GetDeviceStatesResponse.devices:type_name -> pkg.proto.telemetry.v2.DeviceState
	2,  // 9: pkg.proto.telemetry.v2.ListReadingsRequest.range:type_name -> pkg.proto.telemetry.v2.TimeRange
	3,  // 10: pkg.proto.telemetry.v2.ListReadingsRequest.scope:type_name -> pkg.proto.telemetry.v2.Scope
	6,  // 11: pkg.proto.telemetry.v2.ListReadingsResponse.rows:type_name -> pkg.proto.telemetry.v2.Row
	2,  // 12: pkg.proto.telemetry.v2.GetSeriesRequest.range:type_name -> pkg.proto.telemetry.v2.TimeRange
	0,  // 13: pkg.proto.telemetry.v2.GetSeriesRequest.interval:type_name -> pkg.proto.telemetry.v2.Interval
	1,  // 14: pkg.proto.telemetry.v2.GetSeriesRequest.metrics:type_name -> pkg.proto.telemetry.v2.Metric
	3,  // 15: pkg.proto.telemetry.v2.GetSeriesRequest.scope:type_name -> pkg.proto.telemetry.v2.Scope
	22, // 16: pkg.proto.telemetry.v2.Point.ts:type_name -> google.protobuf.Timestamp
	0,  // 17: pkg.proto.telemetry.v2.Series.interval:type_name -> pkg.proto.telemetry.v2.Interval
	14, // 18: pkg.proto.telemetry.v2.Series.points:type_name -> pkg.proto.telemetry.v2.Point
	15, // 19: pkg.proto.telemetry.v2.GetSeriesResponse.series:type_name -> pkg.proto.telemetry.v2.Series
	2,  // 20: pkg.proto.telemetry.v2.GetSummariesRequest.range:type_name -> pkg.proto.telemetry.v2.TimeRange
	3,  // 21: pkg.proto.telemetry.v2.GetSummariesRequest.scope:type_name -> pkg.proto.telemetry.v2.Scope
	22, // 22: pkg.proto.telemetry.v2.Summary.first_ts:type_name -> google.protobuf.Timestamp
	22, // 23: pkg.proto.telemetry.v2.Summary.last_ts:type_name -> google.protobuf.Timestamp
	18, // 24: pkg.proto.telemetry.v2.GetSummariesResponse.summaries:type_name -> pkg.proto.telemetry.v2.Summary
	2,  // 25: pkg.proto.telemetry.v2.ExportReadingsRequest.range:type_name -> pkg.proto.telemetry.v2.TimeRange
	3,  // 26: pkg.proto.telemetry.v2.ExportReadingsRequest.scope:type_name -> pkg.proto.telemetry.v2.Scope
	6,  // 27: pkg.proto.telemetry.v2.ExportReadingsResponse.rows:type_name -> pkg.proto.telemetry.v2.Row
	7,  // 28: pkg.proto.telemetry.v2.DeviceTelemetry.GetDeviceStates:input_type -> pkg.proto.telemetry.v2.GetDeviceStatesRequest
	11, // 29: pkg.proto.telemetry.v2.DeviceTelemetry.ListReadings:input_type -> pkg.proto.telemetry.v2.ListReadingsRequest
	13, // 30: pkg.proto.telemetry.v2.DeviceTelemetry.GetSeries:input_type -> pkg.proto.telemetry.v2.GetSeriesRequest
	17, // 31: pkg.proto.telemetry.v2.DeviceTelemetry.GetSummaries:input_type -> pkg.proto.telemetry.v2.GetSummariesRequest
	20, // 32: pkg.proto.telemetry.v2.DeviceTelemetry.ExportReadings:input_type -> pkg.proto.telemetry.v2.ExportReadingsRequest
	10, // 33: pkg.proto.telemetry.v2.DeviceTelemetry.GetDeviceStates:output_type -> pkg.proto.telemetry.v2.GetDeviceStatesResponse
	12, // 34: pkg.proto.telemetry.v2.DeviceTelemetry.ListReadings:output_type -> pkg.proto.telemetry.v2.ListReadingsResponse
	16, // 35: pkg.proto.telemetry.v2.DeviceTelemetry.GetSeries:output_type -> pkg.proto.telemetry.v2.GetSeriesResponse
	19, // 36: pkg.proto.telemetry.v2.DeviceTelemetry.GetSummaries:output_type -> pkg.proto.telemetry.v2.GetSummariesResponse
	21, // 37: pkg.proto.telemetry.v2.DeviceTelemetry.ExportReadings:output_type -> pkg.proto.telemetry.v2.ExportReadingsResponse
	33, // [33:38] is the sub-list for method output_type
	28, // [28:33] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_pkg_proto_telemetry_v2_device_telemetry_proto_init() }
func file_pkg_proto_telemetry_v2_device_telemetry_proto_init() {
	if File_pkg_proto_telemetry_v2_device_telemetry_proto != nil {
		return
	}
	file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[3].OneofWrappers = []any{}
	file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[12].OneofWrappers = []any{}
	file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDesc), len(file_pkg_proto_telemetry_v2_device_telemetry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_telemetry_v2_device_telemetry_proto_goTypes,
		DependencyIndexes: file_pkg_proto_telemetry_v2_device_telemetry_proto_depIdxs,
		EnumInfos:         file_pkg_proto_telemetry_v2_device_telemetry_proto_enumTypes,
		MessageInfos:      file_pkg_proto_telemetry_v2_device_telemetry_proto_msgTypes,
	}.Build()
	File_pkg_proto_telemetry_v2_device_telemetry_proto = out.File
	file_pkg_proto_telemetry_v2_device_telemetry_proto_goTypes = nil
	file_pkg_proto_telemetry_v2_device_telemetry_proto_depIdxs = nil
}
